from __future__ import annotations
import base64
import json
import re
import urllib.request

BASE_BLOB_URL = "https://api.github.com/repos/gear66me-ui/Galaxy_Viewer/git/blobs/2e2829d05c5fba6bd5b0ffc431987612eebe1aee"
with urllib.request.urlopen(BASE_BLOB_URL, timeout=60) as response:
    payload = json.loads(response.read().decode("utf-8"))
source = base64.b64decode(payload["content"]).decode("utf-8")
source = source.replace("Galaxy Viewer — VIEWER-9-1", "Galaxy Viewer — VIEWER-9-8 GEMINI", 1)
source = source.replace("import urllib.error\nimport urllib.request", "import urllib.error\nimport urllib.request\nimport re", 1)

backend = base64.b64decode("ZGVmIF9nZW1pbmlfZ3JvdW5kZWRfdGV4dChwcm9tcHQ6IHN0cikgLT4gc3RyOgogICAgYXBpX2tleSA9IF9zZWNyZXQoIkdlbWluaSBBUEkgS2V5Iikgb3IgX3NlY3JldCgiR0VNSU5JX0FQSV9LRVkiKQogICAgaWYgbm90IGFwaV9rZXk6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCdBZGQgdGhlIENvbGFiIHNlY3JldCBuYW1lZCBleGFjdGx5ICJHZW1pbmkgQVBJIEtleSIgYW5kIGVuYWJsZSBub3RlYm9vayBhY2Nlc3MuJykKICAgIGJvZHkgPSB7CiAgICAgICAgImNvbnRlbnRzIjogW3sicGFydHMiOiBbeyJ0ZXh0IjogcHJvbXB0fV19XSwKICAgICAgICAidG9vbHMiOiBbeyJnb29nbGVfc2VhcmNoIjoge319XSwKICAgICAgICAiZ2VuZXJhdGlvbkNvbmZpZyI6IHsidGVtcGVyYXR1cmUiOiAwLjl9LAogICAgfQogICAgcmVxdWVzdCA9IHVybGxpYi5yZXF1ZXN0LlJlcXVlc3QoCiAgICAgICAgImh0dHBzOi8vZ2VuZXJhdGl2ZWxhbmd1YWdlLmdvb2dsZWFwaXMuY29tL3YxYmV0YS9tb2RlbHMvZ2VtaW5pLTIuNS1mbGFzaDpnZW5lcmF0ZUNvbnRlbnQiLAogICAgICAgIGRhdGE9anNvbi5kdW1wcyhib2R5KS5lbmNvZGUoInV0Zi04IiksCiAgICAgICAgaGVhZGVycz17IngtZ29vZy1hcGkta2V5IjogYXBpX2tleSwgIkNvbnRlbnQtVHlwZSI6ICJhcHBsaWNhdGlvbi9qc29uIn0sCiAgICAgICAgbWV0aG9kPSJQT1NUIiwKICAgICkKICAgIHRyeToKICAgICAgICB3aXRoIHVybGxpYi5yZXF1ZXN0LnVybG9wZW4ocmVxdWVzdCwgdGltZW91dD03NSkgYXMgcmVzcG9uc2U6CiAgICAgICAgICAgIHJlc3VsdCA9IGpzb24ubG9hZHMocmVzcG9uc2UucmVhZCgpLmRlY29kZSgidXRmLTgiKSkKICAgIGV4Y2VwdCB1cmxsaWIuZXJyb3IuSFRUUEVycm9yIGFzIGV4YzoKICAgICAgICBkZXRhaWwgPSBleGMucmVhZCgpLmRlY29kZSgidXRmLTgiLCBlcnJvcnM9InJlcGxhY2UiKQogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIkdlbWluaSBBUEkgZXJyb3Ige2V4Yy5jb2RlfToge2RldGFpbFs6MTIwMF19IikgZnJvbSBleGMKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcihmIkdlbWluaSByZXF1ZXN0IGZhaWxlZDoge2V4Y30iKSBmcm9tIGV4YwogICAgY2FuZGlkYXRlcyA9IHJlc3VsdC5nZXQoImNhbmRpZGF0ZXMiKSBvciBbXQogICAgaWYgbm90IGNhbmRpZGF0ZXM6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCJHZW1pbmkgcmV0dXJuZWQgbm8gY2FuZGlkYXRlOiAiICsganNvbi5kdW1wcyhyZXN1bHQuZ2V0KCJwcm9tcHRGZWVkYmFjayIpIG9yIHt9KVs6ODAwXSkKICAgIHBhcnRzID0gKChjYW5kaWRhdGVzWzBdLmdldCgiY29udGVudCIpIG9yIHt9KS5nZXQoInBhcnRzIikgb3IgW10pCiAgICB0ZXh0ID0gIlxuIi5qb2luKHN0cihwYXJ0LmdldCgidGV4dCIsICIiKSkgZm9yIHBhcnQgaW4gcGFydHMgaWYgcGFydC5nZXQoInRleHQiKSkuc3RyaXAoKQogICAgaWYgbm90IHRleHQ6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCJHZW1pbmkgcmV0dXJuZWQgbm8gZ3JvdW5kZWQgdGV4dC4iKQogICAgcmV0dXJuIHRleHQKCl9MQVNUX1JBTkRPTV9OQU1FID0gIlBpbndoZWVsIEdhbGF4eSAoTTEwMSkiCgpkZWYgdmlld2VyOV9yYW5kb21fYWkoKToKICAgIGdsb2JhbCBfTEFTVF9SQU5ET01fTkFNRQogICAgdGV4dCA9IF9nZW1pbmlfZ3JvdW5kZWRfdGV4dChmIiIiClVzZSBHb29nbGUgU2VhcmNoIHRvIGNob29zZSBvbmUgcmVhbCwgdmlzdWFsbHkgaW50ZXJlc3RpbmcgZ2FsYXh5IGF0IHJhbmRvbS4KRG8gbm90IGNob29zZSB7X0xBU1RfUkFORE9NX05BTUV9LgpWZXJpZnkgaXRzIElDUlMgZGVjaW1hbCBjb29yZGluYXRlcy4KUmV0dXJuIGV4YWN0bHkgdGhlc2UgZml2ZSBsYWJlbGVkIGxpbmVzIGFuZCBub3RoaW5nIGVsc2U6Ck5BTUU6IGNvbW1vbiBnYWxheHkgbmFtZQpSQTogZGVjaW1hbCBkZWdyZWVzCkRFQzogZGVjaW1hbCBkZWdyZWVzCkZPVjogZmllbGQgb2YgdmlldyBpbiBkZWdyZWVzIHRoYXQgZnJhbWVzIHRoZSBjb21wbGV0ZSB2aXNpYmxlIGdhbGF4eQpTVVJWRVlfSUQ6IG9uZSBvZiBDRFMvUC9IU1QvRVBPLCBQL0RTUzIvY29sb3IsIFAvRFNTMi9yZWQsIFAvUGFuU1RBUlJTL0RSMC9jb2xvci16LXpnLWcsIFAvREVDYUxTL0RSNS9jb2xvciwgUC8yTUFTUy9jb2xvciwgUC9HQUxFWEdSNi9BSVMvY29sb3IKIiIiKQogICAgdmFsdWVzID0ge30KICAgIGZvciBsaW5lIGluIHRleHQuc3BsaXRsaW5lcygpOgogICAgICAgIG1hdGNoID0gcmUubWF0Y2gociJeXHMqKE5BTUV8UkF8REVDfEZPVnxTVVJWRVlfSUQpXHMqOlxzKiguKj8pXHMqJCIsIGxpbmUsIHJlLkkpCiAgICAgICAgaWYgbWF0Y2g6CiAgICAgICAgICAgIHZhbHVlc1ttYXRjaC5ncm91cCgxKS51cHBlcigpXSA9IG1hdGNoLmdyb3VwKDIpLnN0cmlwKCkKICAgIG1pc3NpbmcgPSBba2V5IGZvciBrZXkgaW4gKCJOQU1FIiwgIlJBIiwgIkRFQyIsICJGT1YiLCAiU1VSVkVZX0lEIikgaWYgbm90IHZhbHVlcy5nZXQoa2V5KV0KICAgIGlmIG1pc3Npbmc6CiAgICAgICAgcmFpc2UgUnVudGltZUVycm9yKCJHZW1pbmkgcmFuZG9tLWdhbGF4eSByZXNwb25zZSB3YXMgbWlzc2luZzogIiArICIsICIuam9pbihtaXNzaW5nKSArICIuIFJhdyByZXNwb25zZTogIiArIHRleHRbOjEwMDBdKQogICAgdHJ5OgogICAgICAgIHJlc3VsdCA9IHsKICAgICAgICAgICAgIm5hbWUiOiB2YWx1ZXNbIk5BTUUiXSwKICAgICAgICAgICAgInJhIjogZmxvYXQodmFsdWVzWyJSQSJdKSwKICAgICAgICAgICAgImRlYyI6IGZsb2F0KHZhbHVlc1siREVDIl0pLAogICAgICAgICAgICAiZm92IjogZmxvYXQodmFsdWVzWyJGT1YiXSksCiAgICAgICAgICAgICJzdXJ2ZXlfaWQiOiB2YWx1ZXNbIlNVUlZFWV9JRCJdLAogICAgICAgIH0KICAgIGV4Y2VwdCBWYWx1ZUVycm9yIGFzIGV4YzoKICAgICAgICByYWlzZSBSdW50aW1lRXJyb3IoIkdlbWluaSByZXR1cm5lZCBub24tbnVtZXJpYyBSQSwgRGVjLCBvciBGT1YuIFJhdyByZXNwb25zZTogIiArIHRleHRbOjEwMDBdKSBmcm9tIGV4YwogICAgX0xBU1RfUkFORE9NX05BTUUgPSByZXN1bHRbIm5hbWUiXQogICAgcmV0dXJuIHJlc3VsdAoKZGVmIHZpZXdlcjlfZ2V0X2luZm8obmFtZTogc3RyLCByYTogZmxvYXQsIGRlYzogZmxvYXQpOgogICAgcGFyYW1ldGVycyA9IFsKICAgICAgICAiQ29tbW9uIGRlc2lnbmF0aW9ucyIsCiAgICAgICAgIkNvbnN0ZWxsYXRpb24iLAogICAgICAgICJNb3JwaG9sb2dpY2FsIHR5cGUiLAogICAgICAgICJJQ1JTIGNvb3JkaW5hdGVzIiwKICAgICAgICAiRGlzdGFuY2UiLAogICAgICAgICJEaWFtZXRlciAvIHBoeXNpY2FsIHNpemUiLAogICAgICAgICJSZWRzaGlmdCBhbmQgcmFkaWFsIHZlbG9jaXR5IiwKICAgICAgICAiQXBwYXJlbnQgbWFnbml0dWRlIiwKICAgICAgICAiU3RlbGxhciBtYXNzIG9yIGVzdGltYXRlZCBzdGFyIGNvdW50IiwKICAgICAgICAiRXN0aW1hdGVkIHN0ZWxsYXIgYWdlIiwKICAgIF0KICAgIHRleHQgPSBfZ2VtaW5pX2dyb3VuZGVkX3RleHQoZiIiIgpVc2UgR29vZ2xlIFNlYXJjaCB0byByZXNlYXJjaCB0aGUgZGlzcGxheWVkIGdhbGF4eS4KTmFtZToge25hbWV9CklDUlMgY29vcmRpbmF0ZXM6IFJBIHtmbG9hdChyYSk6LjhmfSBkZWcsIERlYyB7ZmxvYXQoZGVjKTouOGZ9IGRlZy4KVXNlIFNJTUJBRCBmaXJzdCBmb3IgaWRlbnRpZmljYXRpb24sIHRoZW4gTkVEIGFuZCBhdXRob3JpdGF0aXZlIGFzdHJvbm9teSBzb3VyY2VzLgpSZXR1cm4gcGxhaW4gdGV4dCBvbmx5IGluIHRoaXMgZXhhY3QgZm9ybWF0OgpUSVRMRTogY29uY2lzZSB0aXRsZQpTVU1NQVJZOiBjb25jaXNlIHN1bW1hcnkKUk9XOiBDb21tb24gZGVzaWduYXRpb25zIHwgdmFsdWUgfCBub3RlcyB8IHNvdXJjZQpST1c6IENvbnN0ZWxsYXRpb24gfCB2YWx1ZSB8IG5vdGVzIHwgc291cmNlClJPVzogTW9ycGhvbG9naWNhbCB0eXBlIHwgdmFsdWUgfCBub3RlcyB8IHNvdXJjZQpST1c6IElDUlMgY29vcmRpbmF0ZXMgfCB2YWx1ZSB8IG5vdGVzIHwgc291cmNlClJPVzogRGlzdGFuY2UgfCB2YWx1ZSB8IG5vdGVzIHwgc291cmNlClJPVzogRGlhbWV0ZXIgLyBwaHlzaWNhbCBzaXplIHwgdmFsdWUgfCBub3RlcyB8IHNvdXJjZQpST1c6IFJlZHNoaWZ0IGFuZCByYWRpYWwgdmVsb2NpdHkgfCB2YWx1ZSB8IG5vdGVzIHwgc291cmNlClJPVzogQXBwYXJlbnQgbWFnbml0dWRlIHwgdmFsdWUgfCBub3RlcyB8IHNvdXJjZQpST1c6IFN0ZWxsYXIgbWFzcyBvciBlc3RpbWF0ZWQgc3RhciBjb3VudCB8IHZhbHVlIHwgbm90ZXMgfCBzb3VyY2UKUk9XOiBFc3RpbWF0ZWQgc3RlbGxhciBhZ2UgfCB2YWx1ZSB8IG5vdGVzIHwgc291cmNlClVzZSBOb3QgYXZhaWxhYmxlIHdoZW4gdW5zdXBwb3J0ZWQuIERvIG5vdCB1c2UgTWFya2Rvd24gdGFibGVzLgoiIiIpCiAgICB0aXRsZSA9IHN0cihuYW1lKQogICAgc3VtbWFyeSA9ICIiCiAgICBwYXJzZWQgPSB7fQogICAgZm9yIGxpbmUgaW4gdGV4dC5zcGxpdGxpbmVzKCk6CiAgICAgICAgc3RyaXBwZWQgPSBsaW5lLnN0cmlwKCkKICAgICAgICBpZiBzdHJpcHBlZC51cHBlcigpLnN0YXJ0c3dpdGgoIlRJVExFOiIpOgogICAgICAgICAgICB0aXRsZSA9IHN0cmlwcGVkLnNwbGl0KCI6IiwgMSlbMV0uc3RyaXAoKSBvciB0aXRsZQogICAgICAgIGVsaWYgc3RyaXBwZWQudXBwZXIoKS5zdGFydHN3aXRoKCJTVU1NQVJZOiIpOgogICAgICAgICAgICBzdW1tYXJ5ID0gc3RyaXBwZWQuc3BsaXQoIjoiLCAxKVsxXS5zdHJpcCgpCiAgICAgICAgZWxpZiBzdHJpcHBlZC51cHBlcigpLnN0YXJ0c3dpdGgoIlJPVzoiKToKICAgICAgICAgICAgY2VsbHMgPSBbY2VsbC5zdHJpcCgpIGZvciBjZWxsIGluIHN0cmlwcGVkLnNwbGl0KCI6IiwgMSlbMV0uc3BsaXQoInwiLCAzKV0KICAgICAgICAgICAgaWYgbGVuKGNlbGxzKSA9PSA0OgogICAgICAgICAgICAgICAgcGFyc2VkW2NlbGxzWzBdLmxvd2VyKCldID0gewogICAgICAgICAgICAgICAgICAgICJwYXJhbWV0ZXIiOiBjZWxsc1swXSwKICAgICAgICAgICAgICAgICAgICAidmFsdWUiOiBjZWxsc1sxXSBvciAiTm90IGF2YWlsYWJsZSIsCiAgICAgICAgICAgICAgICAgICAgIm5vdGVzIjogY2VsbHNbMl0sCiAgICAgICAgICAgICAgICAgICAgInNvdXJjZSI6IGNlbGxzWzNdLAogICAgICAgICAgICAgICAgfQogICAgcm93cyA9IFtdCiAgICBmb3IgcGFyYW1ldGVyIGluIHBhcmFtZXRlcnM6CiAgICAgICAgcm93ID0gcGFyc2VkLmdldChwYXJhbWV0ZXIubG93ZXIoKSkKICAgICAgICBpZiByb3cgaXMgTm9uZToKICAgICAgICAgICAgcm93ID0geyJwYXJhbWV0ZXIiOiBwYXJhbWV0ZXIsICJ2YWx1ZSI6ICJOb3QgYXZhaWxhYmxlIiwgIm5vdGVzIjogIk5vdCByZXR1cm5lZCBieSBHZW1pbmkgU2VhcmNoLiIsICJzb3VyY2UiOiAiIn0KICAgICAgICBlbHNlOgogICAgICAgICAgICByb3dbInBhcmFtZXRlciJdID0gcGFyYW1ldGVyCiAgICAgICAgcm93cy5hcHBlbmQocm93KQogICAgaWYgbm90IHN1bW1hcnk6CiAgICAgICAgc3VtbWFyeSA9ICJHcm91bmRlZCBHZW1pbmkgU2VhcmNoIHJlc3VsdHMgZm9yIHRoZSBkaXNwbGF5ZWQgZ2FsYXh5LiIKICAgIHJldHVybiB7InRpdGxlIjogdGl0bGUsICJzdW1tYXJ5Ijogc3VtbWFyeSwgInJvd3MiOiByb3dzfQ==").decode("utf-8")
source, count = re.subn(
    r'def _openai_json\(prompt: str, schema_name: str, schema: dict\) -> dict:\n.*?\n\nRANDOM_SCHEMA =',
    lambda match: backend + "\n\nRANDOM_SCHEMA =",
    source,
    count=1,
    flags=re.S,
)
if count != 1:
    raise RuntimeError("VIEWER-9-8 Gemini backend replacement failed")

callbacks = base64.b64decode("ZGVmIHZpZXdlcjlfcmFuZG9tX2NhbGxiYWNrKCk6CiAgICB0cnk6CiAgICAgICAgcmV0dXJuIHsib2siOiBUcnVlLCAicGF5bG9hZCI6IHZpZXdlcjlfcmFuZG9tX2FpKCl9CiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzoKICAgICAgICByZXR1cm4geyJvayI6IEZhbHNlLCAiZXJyb3IiOiBzdHIoZXhjKX0KCmRlZiB2aWV3ZXI5X2luZm9fY2FsbGJhY2sobmFtZTogc3RyLCByYTogZmxvYXQsIGRlYzogZmxvYXQpOgogICAgdHJ5OgogICAgICAgIHJldHVybiB7Im9rIjogVHJ1ZSwgInBheWxvYWQiOiB2aWV3ZXI5X2dldF9pbmZvKG5hbWUsIHJhLCBkZWMpfQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgcmV0dXJuIHsib2siOiBGYWxzZSwgImVycm9yIjogc3RyKGV4Yyl9Cgpjb2xhYl9vdXRwdXQucmVnaXN0ZXJfY2FsbGJhY2soInZpZXdlcjkucmFuZG9tR2FsYXh5QUkiLCB2aWV3ZXI5X3JhbmRvbV9jYWxsYmFjaykKY29sYWJfb3V0cHV0LnJlZ2lzdGVyX2NhbGxiYWNrKCJ2aWV3ZXI5LmdldEdhbGF4eUluZm8iLCB2aWV3ZXI5X2luZm9fY2FsbGJhY2sp").decode("utf-8")
source, count = re.subn(
    r'colab_output\.register_callback\("viewer9\.randomGalaxyAI".*?\ncolab_output\.register_callback\("viewer9\.getGalaxyInfo".*?\)',
    lambda match: callbacks,
    source,
    count=1,
    flags=re.S,
)
if count != 1:
    raise RuntimeError("VIEWER-9-8 callback replacement failed")

random_js = base64.b64decode("YXN5bmMgZnVuY3Rpb24gZ3Y5MVJhbmRvbUdhbGF4eSgpe2d2OTFCdXN5KCJndjkxLXJhbmRvbSIsdHJ1ZSwiU2VhcmNoaW5nLi4uIiwiUmFuZG9tIEdhbGF4eSIpO2d2OTFTdGF0dXMoIkdlbWluaSBTZWFyY2ggaXMgc2VsZWN0aW5nIGFuZCB2ZXJpZnlpbmcgYSByYW5kb20gZ2FsYXh5Li4uIik7dHJ5e2NvbnN0IHI9YXdhaXQgZ29vZ2xlLmNvbGFiLmtlcm5lbC5pbnZva2VGdW5jdGlvbigidmlld2VyOS5yYW5kb21HYWxheHlBSSIsW10se30pO2NvbnN0IHJhdz1yJiZyLmRhdGE/ci5kYXRhOnt9O2xldCBvdXQ9cmF3WyJhcHBsaWNhdGlvbi9qc29uIl0/P3Jhd1sidGV4dC9wbGFpbiJdPz9yYXc7aWYodHlwZW9mIG91dD09PSJzdHJpbmciKXt0cnl7b3V0PUpTT04ucGFyc2Uob3V0KX1jYXRjaChfKXt9fWlmKCFvdXQpdGhyb3cgRXJyb3IoIkNvbGFiIHJldHVybmVkIG5vIGNhbGxiYWNrIHBheWxvYWQuIik7aWYob3V0Lm9rPT09ZmFsc2UpdGhyb3cgRXJyb3Iob3V0LmVycm9yfHwiR2VtaW5pIHJhbmRvbSBzZWFyY2ggZmFpbGVkLiIpO2NvbnN0IGc9b3V0LnBheWxvYWQ/P291dDtpZighZ3x8IU51bWJlci5pc0Zpbml0ZSgrZy5yYSl8fCFOdW1iZXIuaXNGaW5pdGUoK2cuZGVjKXx8IU51bWJlci5pc0Zpbml0ZSgrZy5mb3YpKXRocm93IEVycm9yKCJHZW1pbmkgcmV0dXJuZWQgaW52YWxpZCBnYWxheHkgZGF0YS4iKTtndjkxU2hvd0dhbGF4eShnLCJHZW1pbmkgcmFuZG9tIGdhbGF4eSBsb2FkZWQiKTtkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiZ3Y5MS1wYW5lbCIpLmlubmVySFRNTD0nPGRpdiBjbGFzcz0iaW5mby1sb2FkaW5nIj5QcmVzcyBHZXQgSW5mbyB0byByZXNlYXJjaCAnK2d2OTFFc2MoZy5uYW1lKSsnLjwvZGl2Pid9Y2F0Y2goZSl7Z3Y5MVN0YXR1cygiUmFuZG9tIEdhbGF4eSBmYWlsZWQ6ICIrU3RyaW5nKGUubWVzc2FnZXx8ZSkpfWZpbmFsbHl7Z3Y5MUJ1c3koImd2OTEtcmFuZG9tIixmYWxzZSwiIiwiUmFuZG9tIEdhbGF4eSIpfX0=").decode("utf-8")
source, count = re.subn(
    r'async function gv91RandomGalaxy\(\)\{.*?\}\nasync function gv91GetInfo',
    lambda match: random_js + "\nasync function gv91GetInfo",
    source,
    count=1,
    flags=re.S,
)
if count != 1:
    raise RuntimeError("VIEWER-9-8 Random Galaxy replacement failed")

info_js = base64.b64decode("YXN5bmMgZnVuY3Rpb24gZ3Y5MUdldEluZm8oKXtndjkxQnVzeSgiZ3Y5MS1pbmZvIix0cnVlLCJSZXNlYXJjaGluZy4uLiIsIkdldCBJbmZvIik7Y29uc3QgcD1kb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiZ3Y5MS1wYW5lbCIpO3AuaW5uZXJIVE1MPSc8ZGl2IGNsYXNzPSJpbmZvLWxvYWRpbmciPkdlbWluaSBTZWFyY2ggaXMgY2hlY2tpbmcgU0lNQkFELCBORUQsIGFuZCBhc3Ryb25vbXkgc291cmNlcy4uLjwvZGl2Pic7dHJ5e2NvbnN0IGM9d2luZG93Lmd2OTFBbGFkaW4uZ2V0UmFEZWMoKSxuPWRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJndjkxLW5hbWUiKS52YWx1ZXx8IkRpc3BsYXllZCBnYWxheHkiO2NvbnN0IHI9YXdhaXQgZ29vZ2xlLmNvbGFiLmtlcm5lbC5pbnZva2VGdW5jdGlvbigidmlld2VyOS5nZXRHYWxheHlJbmZvIixbbiwrY1swXSwrY1sxXV0se30pO2NvbnN0IHJhdz1yJiZyLmRhdGE/ci5kYXRhOnt9O2xldCBvdXQ9cmF3WyJhcHBsaWNhdGlvbi9qc29uIl0/P3Jhd1sidGV4dC9wbGFpbiJdPz9yYXc7aWYodHlwZW9mIG91dD09PSJzdHJpbmciKXt0cnl7b3V0PUpTT04ucGFyc2Uob3V0KX1jYXRjaChfKXt9fWlmKCFvdXQpdGhyb3cgRXJyb3IoIkNvbGFiIHJldHVybmVkIG5vIGNhbGxiYWNrIHBheWxvYWQuIik7aWYob3V0Lm9rPT09ZmFsc2UpdGhyb3cgRXJyb3Iob3V0LmVycm9yfHwiR2VtaW5pIEdldCBJbmZvIGZhaWxlZC4iKTtjb25zdCBkPW91dC5wYXlsb2FkPz9vdXQ7aWYoIWR8fCFBcnJheS5pc0FycmF5KGQucm93cykpdGhyb3cgRXJyb3IoIkdlbWluaSByZXR1cm5lZCBubyBpbmZvcm1hdGlvbiByb3dzLiIpO2NvbnN0IHJvd3M9ZC5yb3dzLm1hcCh4PT5gPHRyPjx0ZD4ke2d2OTFFc2MoeC5wYXJhbWV0ZXIpfTwvdGQ+PHRkPiR7Z3Y5MUVzYyh4LnZhbHVlKX08L3RkPjx0ZD4ke2d2OTFFc2MoeC5ub3Rlcyl9PC90ZD48dGQ+JHtndjkxRXNjKHguc291cmNlKX08L3RkPjwvdHI+YCkuam9pbigiIik7cC5pbm5lckhUTUw9YDxkaXYgY2xhc3M9ImluZm8taGVhZCI+PGRpdiBjbGFzcz0iaW5mby10aXRsZSI+JHtndjkxRXNjKGQudGl0bGV8fG4pfTwvZGl2PjxwIGNsYXNzPSJpbmZvLXN1bW1hcnkiPiR7Z3Y5MUVzYyhkLnN1bW1hcnl8fCIiKX08L3A+PC9kaXY+PHRhYmxlIGNsYXNzPSJpbmZvLXRhYmxlIj48dGhlYWQ+PHRyPjx0aD5QYXJhbWV0ZXI8L3RoPjx0aD5WYWx1ZTwvdGg+PHRoPk5vdGVzPC90aD48dGg+U291cmNlPC90aD48L3RyPjwvdGhlYWQ+PHRib2R5PiR7cm93c308L3Rib2R5PjwvdGFibGU+YDtndjkxU3RhdHVzKCJHYWxheHkgaW5mb3JtYXRpb24gcG9wdWxhdGVkIGJ5IEdlbWluaSBTZWFyY2guIil9Y2F0Y2goZSl7Y29uc3QgdGV4dD1TdHJpbmcoZS5tZXNzYWdlfHxlKTtwLmlubmVySFRNTD0nPGRpdiBjbGFzcz0iaW5mby1lcnJvciI+JytndjkxRXNjKHRleHQpKyc8L2Rpdj4nO2d2OTFTdGF0dXMoIkdldCBJbmZvIGZhaWxlZDogIit0ZXh0KX1maW5hbGx5e2d2OTFCdXN5KCJndjkxLWluZm8iLGZhbHNlLCIiLCJHZXQgSW5mbyIpfX0=").decode("utf-8")
source, count = re.subn(
    r'async function gv91GetInfo\(\)\{.*?\}\n\(async\(\)=>',
    lambda match: info_js + "\n(async()=>",
    source,
    count=1,
    flags=re.S,
)
if count != 1:
    raise RuntimeError("VIEWER-9-8 Get Info replacement failed")

source = source.replace(
    'gv91Status("Viewer ready.")})().catch',
    'gv91Status("Viewer ready. Loading a Gemini random galaxy...");setTimeout(gv91RandomGalaxy,500)})().catch',
    1,
)

for forbidden in ["OPENAI_API_KEY", "api.openai.com", "GV97_GALAXIES", "<iframe"]:
    if forbidden in source:
        raise RuntimeError(f"VIEWER-9-8 forbidden behavior remains: {forbidden}")

for required in [
    '"Gemini API Key"',
    "gemini-2.5-flash:generateContent",
    '"google_search": {}',
    'google.colab.kernel.invokeFunction("viewer9.randomGalaxyAI"',
    'google.colab.kernel.invokeFunction("viewer9.getGalaxyInfo"',
    "display(HTML(page))",
    "setTimeout(gv91RandomGalaxy,500)",
]:
    if required not in source:
        raise RuntimeError(f"VIEWER-9-8 required behavior missing: {required}")

compile(source, "VIEWER-9-8.py", "exec")
exec(compile(source, "VIEWER-9-8.py", "exec"))
