from IPython.display import HTML, Javascript, display

# GV-beta-0006N
# Standalone Galaxy Viewer release created from the exact current GV-beta-0006H baseline.
# Changes only the approved uniform 5% coordinate glyph side spacing and V-6N label.

display(HTML("""
<link rel="stylesheet" href="https://aladin.cds.unistra.fr/AladinLite/api/v3/3.8.2/aladin.min.css" />
<style>
@font-face{
    font-family:"Space Age";
    src:url("https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/viewer/artwork/Fonts/Galactic/galactic.otf?v=6N-uniform-glyph-spacing-001") format("opentype");
    font-style:normal;font-weight:400;font-display:block;
}
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000}
#aladin-cosmic-command-test{width:100%;height:100vh;height:100dvh;position:relative!important}
#aladin-cosmic-command-test,
#aladin-cosmic-command-test *{font-family:"Space Age",sans-serif!important;text-transform:uppercase!important}
#aladin-cosmic-command-test .gv-space-age-glyph{display:inline-block!important;transform:scaleY(1.5)!important;transform-origin:center!important}
#aladin-cosmic-command-test input{text-transform:uppercase!important;transform:scaleY(1.5)!important;transform-origin:center!important}
#aladin-cosmic-command-test button,
#aladin-cosmic-command-test input,
#aladin-cosmic-command-test .aladin-location,
#aladin-cosmic-command-test .aladin-coordinates,
#aladin-cosmic-command-test .aladin-logo,
#aladin-cosmic-command-test .aladin-copyright,
#aladin-cosmic-command-test .aladin-fov,
#aladin-cosmic-command-test .aladin-status-bar,
#aladin-cosmic-command-test [class*="Control"],
#aladin-cosmic-command-test [class*="control"],
#aladin-cosmic-command-test [class*="reticle"]{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
#aladin-cosmic-command-test #gv-center-reticle{position:absolute!important;left:50%!important;top:50%!important;z-index:7050!important;width:32px!important;height:32px!important;display:block!important;visibility:visible!important;opacity:1!important;pointer-events:none!important;user-select:none!important;-webkit-user-drag:none!important;transform:translate(-50%,-50%)!important}
#aladin-cosmic-command-test .gv-coordinate-target-row{position:absolute!important;left:12px!important;top:12px!important;z-index:7120!important;display:grid!important;visibility:visible!important;opacity:1!important;align-items:center!important;grid-template-columns:36px minmax(0,1fr) 36px!important;column-gap:2px!important;row-gap:0!important;width:calc(100% - 24px)!important;max-width:366px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;pointer-events:auto!important}
#aladin-cosmic-command-test .gv-native-coordinate-frame{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
#aladin-cosmic-command-test button.gv-menu-proxy,
#aladin-cosmic-command-test button.gv-menu-proxy:hover,
#aladin-cosmic-command-test button.gv-menu-proxy:focus,
#aladin-cosmic-command-test button.gv-menu-proxy:active{appearance:none!important;-webkit-appearance:none!important;position:relative!important;inset:auto!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;justify-content:center!important;width:36px!important;min-width:36px!important;max-width:36px!important;height:36px!important;min-height:36px!important;max-height:36px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;overflow:hidden!important;background:rgba(0,0,0,.82)!important;border:1px solid #D7F4FF!important;border-radius:6px!important;cursor:pointer!important;touch-action:manipulation!important;outline:none!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;pointer-events:auto!important}
#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track{position:absolute!important;left:9px!important;width:18px!important;height:2px!important;border-radius:2px!important;background:#D7F3FF!important;pointer-events:none!important;animation:gv-menu-track-pulse 3.2s ease-in-out infinite!important}
#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track:nth-child(1){top:10px!important}
#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track:nth-child(2){top:17px!important}
#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track:nth-child(3){top:24px!important}
@keyframes gv-menu-track-pulse{0%,100%{box-shadow:0 0 2px rgba(215,243,255,.42),0 0 4px rgba(98,216,255,.22);filter:brightness(.88)}50%{box-shadow:0 0 4px rgba(215,243,255,.96),0 0 9px rgba(98,216,255,.78);filter:brightness(1.18)}}
#aladin-cosmic-command-test .gv-viewer-menu{position:absolute!important;left:12px!important;top:50px!important;z-index:7115!important;display:flex!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important;flex-direction:column!important;align-items:flex-start!important;gap:2px!important;width:184px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;transform:translateY(-4px)!important;transition:opacity .18s ease,transform .18s ease,visibility 0s linear .18s!important}
#aladin-cosmic-command-test .gv-viewer-menu.gv-open{visibility:visible!important;opacity:1!important;pointer-events:auto!important;transform:translateY(0)!important;transition:opacity .18s ease,transform .18s ease!important}
#aladin-cosmic-command-test .gv-viewer-menu-row{display:grid!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;grid-template-columns:146px 36px!important;column-gap:2px!important;align-items:center!important;width:184px!important;height:36px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;isolation:isolate!important}
#aladin-cosmic-command-test .gv-viewer-menu-label,
#aladin-cosmic-command-test .gv-viewer-menu-icon{appearance:none!important;-webkit-appearance:none!important;position:relative!important;inset:auto!important;z-index:1!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;height:36px!important;min-height:36px!important;max-height:36px!important;margin:0!important;box-sizing:border-box!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.86)!important;color:#D7F3FF!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;pointer-events:auto!important;cursor:pointer!important;touch-action:manipulation!important;outline:none!important;transition:background .22s ease,box-shadow .22s ease,filter .22s ease!important}
#aladin-cosmic-command-test .gv-viewer-menu-label{width:146px!important;min-width:146px!important;max-width:146px!important;justify-content:flex-start!important;padding:0 10px!important;font:400 12px/1.15 "Space Age",sans-serif!important;letter-spacing:.55px!important;text-shadow:0 0 2px rgba(234,248,255,.58)!important;text-align:left!important;white-space:nowrap!important;overflow:hidden!important}
#aladin-cosmic-command-test .gv-viewer-menu-icon{width:36px!important;min-width:36px!important;max-width:36px!important;justify-content:center!important;padding:0!important}
#aladin-cosmic-command-test .gv-viewer-menu-row.gv-selected .gv-viewer-menu-label,
#aladin-cosmic-command-test .gv-viewer-menu-row.gv-selected .gv-viewer-menu-icon{z-index:2!important;background:rgba(35,31,70,.96)!important;box-shadow:0 0 5px rgba(240,237,255,.96),0 0 13px rgba(98,216,255,.90),inset 0 0 8px rgba(215,243,255,.24)!important;filter:brightness(1.18)!important}
#aladin-cosmic-command-test .gv-coordinate-target-row>.aladin-location,
#aladin-cosmic-command-test .gv-coordinate-target-row>.aladin-coordinates{position:relative!important;inset:auto!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;width:100%!important;min-width:0!important;max-width:none!important;height:36px!important;min-height:36px!important;max-height:36px!important;margin:0!important;padding:0 8px!important;box-sizing:border-box!important;overflow:hidden!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.86)!important;color:#62D8FF!important;font:400 12px/1.15 "Space Age",sans-serif!important;text-shadow:0 0 6px rgba(98,216,255,.58)!important;box-shadow:0 0 10px rgba(98,216,255,.44)!important;pointer-events:auto!important}
#aladin-cosmic-command-test .gv-coordinate-target-row>.aladin-location input,
#aladin-cosmic-command-test .gv-coordinate-target-row>.aladin-coordinates input{display:block!important;visibility:visible!important;opacity:1!important;width:100%!important;height:100%!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;color:#62D8FF!important;font:400 12px/1.15 "Space Age",sans-serif!important;text-align:center!important;text-shadow:0 0 6px rgba(98,216,255,.58)!important;pointer-events:auto!important}
#aladin-cosmic-command-test .gv-coordinate-target-row>.gv-coordinate-presented input:not(:focus){color:transparent!important;text-shadow:none!important;caret-color:transparent!important}
#aladin-cosmic-command-test .gv-coordinate-target-row>.gv-coordinate-presented{overflow:visible!important}
#aladin-cosmic-command-test .gv-coordinate-display{position:absolute!important;inset:0!important;z-index:2!important;display:grid!important;grid-template-columns:auto minmax(0,1fr) auto minmax(0,1fr)!important;align-items:center!important;column-gap:6px!important;padding:0 8px!important;box-sizing:border-box!important;overflow:visible!important;color:#62D8FF!important;font:400 15px/20px "Space Age",sans-serif!important;letter-spacing:0!important;white-space:nowrap!important;pointer-events:none!important;transform:none!important;animation:gv-target-status-pulse 3s cubic-bezier(.35,.02,.18,1) infinite!important;will-change:filter!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-frame-label{justify-self:start!important;display:inline-flex!important;align-items:center!important;column-gap:.8px!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-axis{min-width:0!important;display:inline-flex!important;align-items:center!important;column-gap:1.1px!important;font-variant-numeric:normal!important;font-feature-settings:normal!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-glyph{display:inline-flex!important;align-items:center!important;justify-content:center!important;height:20px!important;line-height:20px!important;padding-left:.05em!important;padding-right:.05em!important;transform:scaleY(1.4)!important;transform-origin:center!important;overflow:visible!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-digit{width:.72em!important;min-width:.72em!important;max-width:.72em!important;flex:0 0 .72em!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-symbol{width:.46em!important;min-width:.46em!important;max-width:.46em!important;flex:0 0 .46em!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-sign{width:.62em!important;min-width:.62em!important;max-width:.62em!important;flex:0 0 .62em!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-longitude{justify-self:end!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-divider{justify-self:center!important;overflow:visible!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-latitude{justify-self:start!important}
#aladin-cosmic-command-test .gv-coordinate-display.gv-coordinate-moving{animation:none!important;filter:none!important;text-shadow:none!important;will-change:auto!important}
#aladin-cosmic-command-test .gv-coordinate-presented:focus-within .gv-coordinate-display{display:none!important}
#aladin-cosmic-command-test button.gv-target-proxy,
#aladin-cosmic-command-test button.gv-target-proxy:hover,
#aladin-cosmic-command-test button.gv-target-proxy:focus,
#aladin-cosmic-command-test button.gv-target-proxy:active{appearance:none!important;-webkit-appearance:none!important;position:relative!important;inset:auto!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;justify-content:center!important;width:36px!important;min-width:36px!important;max-width:36px!important;height:36px!important;min-height:36px!important;max-height:36px!important;flex:0 0 36px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;overflow:hidden!important;background:rgba(0,0,0,.82)!important;border:1px solid #D7F4FF!important;border-radius:6px!important;cursor:pointer!important;touch-action:manipulation!important;outline:none!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;pointer-events:auto!important}
#aladin-cosmic-command-test button.gv-target-proxy::before{content:"";position:absolute;inset:0;z-index:0;border-radius:5px;pointer-events:none;opacity:0}
#aladin-cosmic-command-test button.gv-target-proxy img{position:relative!important;z-index:2!important;display:block!important;width:34px!important;height:34px!important;object-fit:contain!important;filter:none!important;pointer-events:none!important;user-select:none!important;-webkit-user-drag:none!important}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet{position:absolute!important;left:50%!important;top:50%!important;width:0!important;height:0!important;animation:gv-target-comet-orbit 2.8s linear infinite!important;pointer-events:none!important;z-index:3!important}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i{position:absolute!important;left:-2px!important;top:-2px!important;width:4px!important;height:4px!important;border-radius:50%!important;background:#62D8FF!important;transform:rotate(var(--gv-angle)) translateY(-13px) scale(var(--gv-scale))!important;opacity:var(--gv-opacity)!important;box-shadow:0 0 4px rgba(98,216,255,.85)!important}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(1){--gv-angle:0deg;--gv-scale:1;--gv-opacity:1;background:#FFFFFF!important;box-shadow:0 0 3px 1px #FFFFFF,0 0 7px 2px #62D8FF!important}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(2){--gv-angle:-15deg;--gv-scale:.88;--gv-opacity:.84}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(3){--gv-angle:-30deg;--gv-scale:.76;--gv-opacity:.68}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(4){--gv-angle:-45deg;--gv-scale:.64;--gv-opacity:.52}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(5){--gv-angle:-60deg;--gv-scale:.52;--gv-opacity:.38}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(6){--gv-angle:-75deg;--gv-scale:.42;--gv-opacity:.26}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(7){--gv-angle:-90deg;--gv-scale:.32;--gv-opacity:.16}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(8){--gv-angle:-105deg;--gv-scale:.24;--gv-opacity:.08}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"]{box-shadow:0 0 10px rgba(98,216,255,.38)!important}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"]::before{opacity:1;background:radial-gradient(circle at 18% 20%,rgba(218,255,231,.72) 0 2px,rgba(92,255,157,.46) 5px,transparent 11px),radial-gradient(circle at 82% 22%,rgba(183,255,210,.64) 0 2px,rgba(50,244,137,.42) 6px,transparent 12px),radial-gradient(circle at 20% 82%,rgba(146,255,190,.58) 0 2px,rgba(37,226,126,.42) 7px,transparent 13px),radial-gradient(circle at 82% 80%,rgba(199,255,220,.60) 0 2px,rgba(64,249,148,.42) 7px,transparent 13px),radial-gradient(ellipse at center,rgba(40,236,127,.24),rgba(5,39,22,.76) 72%,rgba(0,0,0,.88));box-shadow:inset 0 0 10px rgba(86,255,159,.42),0 0 9px rgba(62,255,145,.48);animation:gv-target-active-well 2.4s ease-in-out infinite}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"] .gv-target-comet{animation-duration:1.4s!important}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"] .gv-target-comet i:nth-child(1){background:#DFFFF0!important;box-shadow:0 0 3px 1px #E8FFF2,0 0 8px 3px #4CFF9B!important}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"] .gv-target-comet i:nth-child(n+2){background:#4CFF9B!important;box-shadow:0 0 5px rgba(76,255,155,.95)!important}
@keyframes gv-target-comet-orbit{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}
@keyframes gv-target-active-well{0%,100%{filter:brightness(.86);box-shadow:inset 0 0 7px rgba(86,255,159,.32),0 0 6px rgba(62,255,145,.34)}50%{filter:brightness(1.18);box-shadow:inset 0 0 15px rgba(115,255,174,.70),0 0 14px rgba(62,255,145,.82)}}
#aladin-cosmic-command-test .gv-target-status{grid-column:2!important;grid-row:2!important;justify-self:end!important;align-self:start!important;display:flex!important;align-items:center!important;justify-content:flex-end!important;min-height:30px!important;margin-top:1px!important;color:#D7F3FF!important;font:400 12px/1.25 "Space Age",sans-serif!important;letter-spacing:.55px!important;text-align:right!important;text-transform:uppercase!important;text-shadow:0 0 5px rgba(98,216,255,.50)!important;pointer-events:auto!important;cursor:pointer!important}
#aladin-cosmic-command-test .gv-target-status:empty{display:none!important}
#aladin-cosmic-command-test .gv-target-status .gv-target-status-text{display:inline-block!important;transform:scaleY(1.5)!important;transform-origin:center!important;white-space:pre-line!important}
#aladin-cosmic-command-test .gv-target-status.gv-clear-ready{color:#B7FFCF!important;text-shadow:0 0 5px rgba(76,255,155,.60)!important}
#aladin-cosmic-command-test #gv-version-label{position:absolute!important;right:12px!important;top:12px!important;z-index:7120!important;display:flex!important;align-items:center!important;justify-content:center!important;width:48px!important;height:36px!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.82)!important;color:var(--gv-version-color,#FFD166)!important;font:400 11px/1.15 "Space Age",sans-serif!important;letter-spacing:.5px!important;text-shadow:0 0 6px var(--gv-version-glow,rgba(255,209,102,.58))!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;pointer-events:none!important}
#aladin-cosmic-command-test #gv-version-label .gv-space-age-glyph{transform:scaleY(1.5)!important}
#aladin-cosmic-command-test #gv-random-galaxy-panel{position:absolute!important;left:12px!important;right:12px!important;bottom:12px!important;z-index:7110!important;display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:8px!important;pointer-events:none!important}
#aladin-cosmic-command-test #gv-random-galaxy-name{min-width:0!important;padding:8px 10px!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.82)!important;color:#D7F3FF!important;font:400 12px/1.2 "Space Age",sans-serif!important;letter-spacing:.55px!important;text-align:left!important;text-shadow:0 0 5px rgba(98,216,255,.50)!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;overflow:hidden!important;white-space:nowrap!important;text-overflow:ellipsis!important}
#aladin-cosmic-command-test #gv-galaxy-navigation{display:flex!important;gap:6px!important;pointer-events:auto!important}
#aladin-cosmic-command-test #gv-galaxy-navigation button{appearance:none!important;-webkit-appearance:none!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;justify-content:center!important;height:36px!important;margin:0!important;padding:0 10px!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.82)!important;color:#D7F3FF!important;font:400 11px/1.15 "Space Age",sans-serif!important;letter-spacing:.45px!important;text-shadow:0 0 5px rgba(98,216,255,.50)!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;cursor:pointer!important;touch-action:manipulation!important}
#aladin-cosmic-command-test #gv-galaxy-navigation button:disabled{opacity:.42!important;cursor:default!important}
</style>
<div id="aladin-cosmic-command-test"></div>
"""))

display(Javascript(r"""
(async()=>{
    const root=document.getElementById("aladin-cosmic-command-test");
    if(!root)return;
    const script=document.createElement("script");
    script.src="https://aladin.cds.unistra.fr/AladinLite/api/v3/3.8.2/aladin.js";
    script.onload=async()=>{
        await A.init;
        const aladin=A.aladin("#aladin-cosmic-command-test",{survey:"P/DSS2/color",fov:1.5,target:"M 31",cooFrame:"ICRSd",projection:"TAN",showReticle:true,reticleColor:"#62D8FF",reticleSize:22,showZoomControl:true,showFullscreenControl:true,showLayersControl:true,showGotoControl:true,showFrame:true,showProjectionControl:true,showCooGridControl:true});
        window.aladin_cosmic_command_test=aladin;
        const findCoordinateBox=()=>root.querySelector(".aladin-location,.aladin-coordinates");
        const findNativeSimbadEngine=()=>root.querySelector("button[title*='SIMBAD' i],button[aria-label*='SIMBAD' i]");
        const wrapVisibleText=scope=>{scope.querySelectorAll("button,#gv-version-label,#gv-random-galaxy-name,.gv-target-status").forEach(element=>{if(element.querySelector(".gv-space-age-glyph"))return;const text=[...element.childNodes].filter(node=>node.nodeType===Node.TEXT_NODE).map(node=>node.textContent).join("").trim();if(!text)return;[...element.childNodes].filter(node=>node.nodeType===Node.TEXT_NODE).forEach(node=>node.remove());const span=document.createElement("span");span.className="gv-space-age-glyph";span.textContent=text;element.appendChild(span)})};
        const formatCoordinatesFourDecimals=()=>{const box=findCoordinateBox();if(!box)return;const input=box.querySelector("input");if(!input)return;const match=String(input.value||"").match(/(-?\d+(?:\.\d+)?)\s*([+\-]\d+(?:\.\d+)?)/);if(!match)return;const longitude=Number(match[1]),latitude=Number(match[2]);if(!Number.isFinite(longitude)||!Number.isFinite(latitude))return;const formatted=`${longitude.toFixed(4)} ${latitude>=0?"+":""}${latitude.toFixed(4)}`;if(input.value!==formatted)input.value=formatted;let display=box.querySelector(".gv-coordinate-display");if(!display){display=document.createElement("div");display.className="gv-coordinate-display";display.setAttribute("aria-hidden","true");box.appendChild(display);box.classList.add("gv-coordinate-presented")}const glyphSpan=(character,extraClass="")=>{const span=document.createElement("span");span.className=`gv-coordinate-glyph ${extraClass}`.trim();span.textContent=character;return span};const fillAxis=(container,value)=>{container.replaceChildren();[...value].forEach(character=>{const extra=/\d/.test(character)?"gv-coordinate-digit":character==="."?"gv-coordinate-symbol":"gv-coordinate-sign";container.appendChild(glyphSpan(character,extra))})};let frame=display.querySelector(".gv-coordinate-frame-label"),lon=display.querySelector(".gv-coordinate-longitude"),divider=display.querySelector(".gv-coordinate-divider"),lat=display.querySelector(".gv-coordinate-latitude");if(!frame){frame=document.createElement("span");frame.className="gv-coordinate-frame-label";frame.append(glyphSpan("G"),glyphSpan("A"),glyphSpan("L"));lon=document.createElement("span");lon.className="gv-coordinate-axis gv-coordinate-longitude";divider=document.createElement("span");divider.className="gv-coordinate-divider";divider.append(glyphSpan("λ"));lat=document.createElement("span");lat.className="gv-coordinate-axis gv-coordinate-latitude";display.append(frame,lon,divider,lat)}fillAxis(lon,longitude.toFixed(4));fillAxis(lat,`${latitude>=0?"+":""}${latitude.toFixed(4)}`);display.classList.add("gv-coordinate-moving");clearTimeout(display._gvCoordinateSettleTimer);display._gvCoordinateSettleTimer=setTimeout(()=>display.classList.remove("gv-coordinate-moving"),300)};
        function createMenuProxy(){let button=root.querySelector(".gv-menu-proxy");if(button)return button;button=document.createElement("button");button.type="button";button.className="gv-menu-proxy";button.setAttribute("aria-label","GALAXY VIEWER MENU");button.innerHTML='<span class="gv-menu-track"></span><span class="gv-menu-track"></span><span class="gv-menu-track"></span>';button.addEventListener("click",()=>{const menu=getViewerMenu();menu.classList.toggle("gv-open")});return button}
        function getViewerMenu(){let menu=root.querySelector(".gv-viewer-menu");if(menu)return menu;menu=document.createElement("div");menu.className="gv-viewer-menu";const rows=[["LAYERS","◉"],["WORLD","◎"],["PROJECTION","◇"],["FULLSCREEN","□"],["ZOOM IN","+"],["ZOOM OUT","−"]];rows.forEach(([label,icon],index)=>{const row=document.createElement("div");row.className="gv-viewer-menu-row";const labelButton=document.createElement("button");labelButton.type="button";labelButton.className="gv-viewer-menu-label";labelButton.textContent=label;const iconButton=document.createElement("button");iconButton.type="button";iconButton.className="gv-viewer-menu-icon";iconButton.textContent=icon;const action=()=>{menu.querySelectorAll(".gv-viewer-menu-row").forEach(item=>item.classList.remove("gv-selected"));row.classList.add("gv-selected");if(index===3)document.documentElement.requestFullscreen?.();if(index===4)aladin.increaseZoom?.();if(index===5)aladin.decreaseZoom?.()};labelButton.addEventListener("click",action);iconButton.addEventListener("click",action);row.append(labelButton,iconButton);menu.appendChild(row)});root.appendChild(menu);wrapVisibleText(menu);return menu}
        function createTargetProxy(){let proxy=root.querySelector(".gv-target-proxy");if(proxy)return proxy;proxy=document.createElement("button");proxy.type="button";proxy.className="gv-target-proxy";proxy.setAttribute("aria-label","TARGET SIMBAD OBJECT");proxy.setAttribute("aria-pressed","false");const image=document.createElement("img");image.src="https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/viewer/artwork/icon_target_vector.svg";image.alt="";const comet=document.createElement("span");comet.className="gv-target-comet";comet.innerHTML="<i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i>";proxy.append(image,comet);return proxy}
        function getTargetStatus(){let status=root.querySelector(".gv-target-status");if(status)return status;status=document.createElement("div");status.className="gv-target-status";status.setAttribute("role","status");status.setAttribute("aria-live","polite");return status}
        function setStatus(status,text,clearReady=false){status.textContent=text;status.classList.toggle("gv-clear-ready",clearReady);wrapVisibleText(status)}
        function bindTargetStatus(proxy,status){if(proxy.dataset.bound)return;proxy.dataset.bound="1";let active=false;proxy.addEventListener("click",()=>{active=!active;proxy.setAttribute("aria-pressed",String(active));setStatus(status,active?"TARGET ACTIVE\nTAP A GALAXY OR STAR":"",false);const native=findNativeSimbadEngine();if(active)native?.click()});status.addEventListener("click",()=>{if(!status.classList.contains("gv-clear-ready"))return;status.textContent="";status.classList.remove("gv-clear-ready");active=false;proxy.setAttribute("aria-pressed","false")});const observer=new MutationObserver(()=>{const popup=root.querySelector(".aladin-popup-container,.aladin-popup");if(popup&&String(popup.textContent||"").trim())setStatus(status,"SIMBAD RESULT DISPLAYED\nTAP HERE TO CLEAR",true)});observer.observe(root,{childList:true,subtree:true})}
        function buildCoordinateTargetRow(){const frame=root.querySelector(".aladin-cooFrame"),coordinateBox=findCoordinateBox(),engine=findNativeSimbadEngine();if(!frame||!coordinateBox||!engine)return false;frame.classList.add("gv-native-coordinate-frame");frame.setAttribute("aria-hidden","true");frame.tabIndex=-1;engine.classList.add("gv-native-simbad-engine");engine.setAttribute("aria-hidden","true");engine.tabIndex=-1;let row=root.querySelector(".gv-coordinate-target-row");if(!row){row=document.createElement("div");row.className="gv-coordinate-target-row";root.appendChild(row)}const menu=createMenuProxy();if(menu.parentElement!==row)row.appendChild(menu);if(coordinateBox.parentElement!==row)row.appendChild(coordinateBox);const proxy=createTargetProxy();if(proxy.parentElement!==row)row.appendChild(proxy);const status=getTargetStatus();if(status.parentElement!==row)row.appendChild(status);getViewerMenu();bindTargetStatus(proxy,status);formatCoordinatesFourDecimals();wrapVisibleText(row);return row.children.length>=4}
        [150,350,700,1200,2200].forEach(delay=>setTimeout(buildCoordinateTargetRow,delay));
        const rowObserver=new MutationObserver(mutations=>{if(mutations.every(mutation=>mutation.target?.closest?.(".gv-coordinate-display")))return;buildCoordinateTargetRow();wrapVisibleText(root)});rowObserver.observe(root,{childList:true,subtree:true});setInterval(formatCoordinatesFourDecimals,250);
        const versionLabel=document.createElement("div");versionLabel.id="gv-version-label";versionLabel.textContent="V-6N";versionLabel.style.setProperty("--gv-version-color","#FFD166");versionLabel.style.setProperty("--gv-version-glow","rgba(255,209,102,.58)");root.appendChild(versionLabel);
        const panel=document.createElement("div");panel.id="gv-random-galaxy-panel";panel.innerHTML='<div id="gv-random-galaxy-name" role="status" aria-live="polite">1,000 GALAXIES · 250 SPECTACULAR</div><div id="gv-galaxy-navigation"><button id="gv-back-galaxy" type="button" disabled>BACK</button><button id="gv-next-galaxy" type="button" disabled>NEXT GALAXY</button></div>';root.appendChild(panel);wrapVisibleText(root);
        const nameLabel=panel.querySelector("#gv-random-galaxy-name"),backButton=panel.querySelector("#gv-back-galaxy"),nextButton=panel.querySelector("#gv-next-galaxy");let history=[],historyPosition=-1,navigating=false;
        function setVisibleText(element,text){element.textContent=String(text).toUpperCase();wrapVisibleText(element)}
        async function loadCatalog(){try{const response=await fetch("https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/discovery/galaxy-catalog-beta.json",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();const galaxies=Array.isArray(data)?data:Array.isArray(data.galaxies)?data.galaxies:[];return galaxies.filter(item=>item&&Number.isFinite(Number(item.ra))&&Number.isFinite(Number(item.dec)))}catch(error){console.warn("GALAXY CATALOG LOAD FAILED",error);return[]}}
        const galaxies=await loadCatalog();
        function labelFor(galaxy){return String(galaxy.name||galaxy.main_id||galaxy.id||"UNKNOWN GALAXY")}
        function showGalaxy(galaxy,recordHistory=true){if(!galaxy||navigating)return;navigating=true;const ra=Number(galaxy.ra),dec=Number(galaxy.dec),fov=Math.max(.18,Number(galaxy.fov)||1.5);aladin.gotoRaDec(ra,dec);aladin.setFoV(fov);setVisibleText(nameLabel,labelFor(galaxy));if(recordHistory){history=history.slice(0,historyPosition+1);history.push(galaxy);historyPosition=history.length-1}backButton.disabled=historyPosition<=0;nextButton.disabled=!galaxies.length;setTimeout(()=>{navigating=false},300)}
        function randomGalaxy(){if(!galaxies.length){setVisibleText(nameLabel,"CATALOGS UNAVAILABLE");return}showGalaxy(galaxies[Math.floor(Math.random()*galaxies.length)],true)}
        backButton.addEventListener("click",()=>{if(historyPosition<=0)return;historyPosition-=1;showGalaxy(history[historyPosition],false);backButton.disabled=historyPosition<=0});
        nextButton.addEventListener("click",randomGalaxy);
        if(galaxies.length)randomGalaxy();else setVisibleText(nameLabel,"CATALOGS UNAVAILABLE");
    };
    document.head.appendChild(script);
})();
"""))

# GV-beta-0006L staged
