from IPython.display import HTML, Javascript, display

# GV-beta-0006T
# Standalone Galaxy Viewer release created from the exact current GV-beta-0006R baseline.
# USER INSTRUCTION: Preserve the Space Age Regular OTF and all approved 6R behavior; increase only the coordinate glyph vertical scale to 1.5, enlarge the top coordinate-control row to 42px for clearance, preserve the compact hamburger bars/menu tiles, and use Mollweide as the default projection.

display(HTML("""
<link rel="stylesheet" href="https://aladin.cds.unistra.fr/AladinLite/api/v3/3.8.2/aladin.min.css" />
<style>
@font-face{
    font-family:"Space Age";
    src:url("https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/viewer/artwork/Fonts/Space%20Age%20Regular/Space%20Age%20Regular.otf?v=6R-space-age-regular-001") format("opentype");
    font-style:normal;font-weight:400;font-display:block;
}
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000}
#aladin-cosmic-command-test{width:100%;height:100vh;height:100dvh;position:relative!important}
#aladin-cosmic-command-test,
#aladin-cosmic-command-test *{font-family:"Space Age",sans-serif!important;text-transform:uppercase!important}
#aladin-cosmic-command-test .gv-space-age-glyph{display:inline-block!important;transform:scaleY(1.5)!important;transform-origin:center!important}
#aladin-cosmic-command-test input{text-transform:uppercase!important;transform:scaleY(1.5)!important;transform-origin:center!important}
#aladin-cosmic-command-test button,
#aladin-cosmic-command-test input,
#aladin-cosmic-command-test .aladin-location,
#aladin-cosmic-command-test .aladin-coordinates,
#aladin-cosmic-command-test .aladin-logo,
#aladin-cosmic-command-test .aladin-copyright,
#aladin-cosmic-command-test .aladin-fov,
#aladin-cosmic-command-test .aladin-status-bar,
#aladin-cosmic-command-test [class*="Control"],
#aladin-cosmic-command-test [class*="control"],
#aladin-cosmic-command-test [class*="reticle"]{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
#aladin-cosmic-command-test #gv-center-reticle{position:absolute!important;left:50%!important;top:50%!important;z-index:7050!important;width:32px!important;height:32px!important;display:block!important;visibility:visible!important;opacity:1!important;pointer-events:none!important;user-select:none!important;-webkit-user-drag:none!important;transform:translate(-50%,-50%)!important}
#aladin-cosmic-command-test .gv-coordinate-target-row{position:absolute!important;left:12px!important;top:12px!important;z-index:7120!important;display:grid!important;visibility:visible!important;opacity:1!important;align-items:center!important;grid-template-columns:42px minmax(0,1fr) 42px!important;column-gap:2px!important;row-gap:0!important;width:calc(100% - 24px)!important;max-width:378px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;pointer-events:auto!important}
#aladin-cosmic-command-test .gv-native-coordinate-frame{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}
#aladin-cosmic-command-test button.gv-menu-proxy,
#aladin-cosmic-command-test button.gv-menu-proxy:hover,
#aladin-cosmic-command-test button.gv-menu-proxy:focus,
#aladin-cosmic-command-test button.gv-menu-proxy:active{appearance:none!important;-webkit-appearance:none!important;position:relative!important;inset:auto!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;justify-content:center!important;width:42px!important;min-width:42px!important;max-width:42px!important;height:42px!important;min-height:42px!important;max-height:42px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;overflow:hidden!important;background:rgba(0,0,0,.82)!important;border:1px solid #D7F4FF!important;border-radius:6px!important;cursor:pointer!important;touch-action:manipulation!important;outline:none!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;pointer-events:auto!important}
#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track{position:absolute!important;left:9px!important;width:18px!important;height:2px!important;border-radius:2px!important;background:#D7F3FF!important;pointer-events:none!important;animation:gv-menu-track-pulse 3.2s ease-in-out infinite!important}
#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track:nth-child(1){top:10px!important}
#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track:nth-child(2){top:17px!important}
#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track:nth-child(3){top:24px!important}
@keyframes gv-menu-track-pulse{0%,100%{box-shadow:0 0 2px rgba(215,243,255,.42),0 0 4px rgba(98,216,255,.22);filter:brightness(.88)}50%{box-shadow:0 0 4px rgba(215,243,255,.96),0 0 9px rgba(98,216,255,.78);filter:brightness(1.18)}}
#aladin-cosmic-command-test .gv-viewer-menu{position:absolute!important;left:12px!important;top:56px!important;z-index:7115!important;display:flex!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important;flex-direction:column!important;align-items:flex-start!important;gap:2px!important;width:184px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;transform:translateY(-4px)!important;transition:opacity .18s ease,transform .18s ease,visibility 0s linear .18s!important}
#aladin-cosmic-command-test .gv-viewer-menu.gv-open{visibility:visible!important;opacity:1!important;pointer-events:auto!important;transform:translateY(0)!important;transition:opacity .18s ease,transform .18s ease!important}
#aladin-cosmic-command-test .gv-viewer-menu-row{display:grid!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;grid-template-columns:146px 36px!important;column-gap:2px!important;align-items:center!important;width:184px!important;height:36px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;isolation:isolate!important}
#aladin-cosmic-command-test .gv-viewer-menu-label,
#aladin-cosmic-command-test .gv-viewer-menu-icon{appearance:none!important;-webkit-appearance:none!important;position:relative!important;inset:auto!important;z-index:1!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;height:36px!important;min-height:36px!important;max-height:36px!important;margin:0!important;box-sizing:border-box!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.86)!important;color:#D7F3FF!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;pointer-events:auto!important;cursor:pointer!important;touch-action:manipulation!important;outline:none!important;transition:background .22s ease,box-shadow .22s ease,filter .22s ease!important}
#aladin-cosmic-command-test .gv-viewer-menu-label{width:146px!important;min-width:146px!important;max-width:146px!important;justify-content:flex-start!important;padding:0 10px!important;font:400 12px/1.15 "Space Age",sans-serif!important;letter-spacing:.55px!important;text-shadow:0 0 2px rgba(234,248,255,.58)!important;text-align:left!important;white-space:nowrap!important;overflow:hidden!important}
#aladin-cosmic-command-test .gv-viewer-menu-icon{width:36px!important;min-width:36px!important;max-width:36px!important;justify-content:center!important;padding:0!important}
#aladin-cosmic-command-test .gv-viewer-menu-row.gv-selected .gv-viewer-menu-label,
#aladin-cosmic-command-test .gv-viewer-menu-row.gv-selected .gv-viewer-menu-icon{z-index:2!important;background:rgba(35,31,70,.96)!important;box-shadow:0 0 5px rgba(240,237,255,.96),0 0 13px rgba(98,216,255,.90),inset 0 0 8px rgba(215,243,255,.24)!important;filter:brightness(1.18)!important}
#aladin-cosmic-command-test .gv-coordinate-target-row>.aladin-location,
#aladin-cosmic-command-test .gv-coordinate-target-row>.aladin-coordinates{position:relative!important;inset:auto!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;width:100%!important;min-width:0!important;max-width:none!important;height:42px!important;min-height:42px!important;max-height:42px!important;margin:0!important;padding:0 8px!important;box-sizing:border-box!important;overflow:hidden!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.86)!important;color:#62D8FF!important;font:400 12px/1.15 "Space Age",sans-serif!important;text-shadow:0 0 6px rgba(98,216,255,.58)!important;box-shadow:0 0 10px rgba(98,216,255,.44)!important;pointer-events:auto!important}
#aladin-cosmic-command-test .gv-coordinate-target-row>.aladin-location input,
#aladin-cosmic-command-test .gv-coordinate-target-row>.aladin-coordinates input{display:block!important;visibility:visible!important;opacity:1!important;width:100%!important;height:100%!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;color:#62D8FF!important;font:400 12px/1.15 "Space Age",sans-serif!important;text-align:center!important;text-shadow:0 0 6px rgba(98,216,255,.58)!important;pointer-events:auto!important}
#aladin-cosmic-command-test .gv-coordinate-target-row>.gv-coordinate-presented input:not(:focus){color:transparent!important;text-shadow:none!important;caret-color:transparent!important}
#aladin-cosmic-command-test .gv-coordinate-target-row>.gv-coordinate-presented{overflow:visible!important}
#aladin-cosmic-command-test .gv-coordinate-display{position:absolute!important;inset:0!important;z-index:2!important;display:grid!important;grid-template-columns:auto minmax(0,1fr) auto minmax(0,1fr)!important;align-items:center!important;column-gap:6px!important;padding:0 8px!important;box-sizing:border-box!important;overflow:visible!important;color:#62D8FF!important;font:400 15px/25px "Space Age",sans-serif!important;letter-spacing:0!important;white-space:nowrap!important;pointer-events:none!important;transform:none!important;animation:none!important;filter:none!important;text-shadow:none!important;will-change:auto!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-frame-label{justify-self:start!important;display:inline-flex!important;align-items:center!important;column-gap:.8px!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-axis{min-width:0!important;display:inline-flex!important;align-items:center!important;column-gap:1.1px!important;font-variant-numeric:normal!important;font-feature-settings:normal!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-glyph{display:inline-flex!important;align-items:center!important;justify-content:center!important;height:25px!important;line-height:25px!important;padding-left:.05em!important;padding-right:.05em!important;transform:scaleY(1.5)!important;transform-origin:center!important;overflow:visible!important;text-shadow:none!important;filter:none!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-digit{width:.72em!important;min-width:.72em!important;max-width:.72em!important;flex:0 0 .72em!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-one{width:.58em!important;min-width:.58em!important;max-width:.58em!important;flex:0 0 .58em!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-symbol{width:.30em!important;min-width:.30em!important;max-width:.30em!important;flex:0 0 .30em!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-sign{width:.62em!important;min-width:.62em!important;max-width:.62em!important;flex:0 0 .62em!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-longitude{justify-self:end!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-divider{justify-self:center!important;overflow:visible!important}
#aladin-cosmic-command-test .gv-coordinate-display .gv-coordinate-latitude{justify-self:start!important}
#aladin-cosmic-command-test .gv-coordinate-display.gv-coordinate-moving{animation:none!important;filter:none!important;text-shadow:none!important;will-change:auto!important}
#aladin-cosmic-command-test .gv-coordinate-presented:focus-within .gv-coordinate-display{display:none!important}
#aladin-cosmic-command-test button.gv-target-proxy,
#aladin-cosmic-command-test button.gv-target-proxy:hover,
#aladin-cosmic-command-test button.gv-target-proxy:focus,
#aladin-cosmic-command-test button.gv-target-proxy:active{appearance:none!important;-webkit-appearance:none!important;position:relative!important;inset:auto!important;display:flex!important;visibility:visible!important;opacity:1!important;align-items:center!important;justify-content:center!important;width:42px!important;min-width:42px!important;max-width:42px!important;height:42px!important;min-height:42px!important;max-height:42px!important;flex:0 0 42px!important;margin:0!important;padding:0!important;box-sizing:border-box!important;overflow:hidden!important;background:rgba(0,0,0,.82)!important;border:1px solid #D7F4FF!important;border-radius:6px!important;cursor:pointer!important;touch-action:manipulation!important;outline:none!important;box-shadow:0 0 10px rgba(98,216,255,.38)!important;pointer-events:auto!important}
#aladin-cosmic-command-test button.gv-target-proxy::before{content:"";position:absolute;inset:0;z-index:0;border-radius:5px;pointer-events:none;opacity:0}
#aladin-cosmic-command-test button.gv-target-proxy img{position:relative!important;z-index:2!important;display:block!important;width:34px!important;height:34px!important;object-fit:contain!important;filter:none!important;pointer-events:none!important;user-select:none!important;-webkit-user-drag:none!important}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet{position:absolute!important;left:50%!important;top:50%!important;width:0!important;height:0!important;animation:gv-target-comet-orbit 2.8s linear infinite!important;pointer-events:none!important;z-index:3!important}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i{position:absolute!important;left:-2px!important;top:-2px!important;width:4px!important;height:4px!important;border-radius:50%!important;background:#62D8FF!important;transform:rotate(var(--gv-angle)) translateY(-13px) scale(var(--gv-scale))!important;opacity:var(--gv-opacity)!important;box-shadow:0 0 4px rgba(98,216,255,.85)!important}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(1){--gv-angle:0deg;--gv-scale:1;--gv-opacity:1;background:#FFFFFF!important;box-shadow:0 0 3px 1px #FFFFFF,0 0 7px 2px #62D8FF!important}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(2){--gv-angle:-15deg;--gv-scale:.88;--gv-opacity:.84}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(3){--gv-angle:-30deg;--gv-scale:.76;--gv-opacity:.68}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(4){--gv-angle:-45deg;--gv-scale:.64;--gv-opacity:.52}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(5){--gv-angle:-60deg;--gv-scale:.52;--gv-opacity:.38}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(6){--gv-angle:-75deg;--gv-scale:.42;--gv-opacity:.26}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(7){--gv-angle:-90deg;--gv-scale:.32;--gv-opacity:.16}
#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet i:nth-child(8){--gv-angle:-105deg;--gv-scale:.24;--gv-opacity:.08}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"]{box-shadow:0 0 10px rgba(98,216,255,.38)!important}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"]::before{opacity:1;background:radial-gradient(circle at 18% 20%,rgba(218,255,231,.72) 0 2px,rgba(92,255,157,.46) 5px,transparent 11px),radial-gradient(circle at 82% 22%,rgba(183,255,210,.64) 0 2px,rgba(50,244,137,.42) 6px,transparent 12px),radial-gradient(circle at 20% 82%,rgba(146,255,190,.58) 0 2px,rgba(37,226,126,.42) 7px,transparent 13px),radial-gradient(circle at 82% 80%,rgba(199,255,220,.60) 0 2px,rgba(64,249,148,.42) 7px,transparent 13px),linear-gradient(145deg,rgba(30,197,110,.97),rgba(65,246,143,.95) 48%,rgba(19,158,88,.98));box-shadow:inset 0 0 8px rgba(164,255,202,.62),inset 0 0 3px rgba(239,255,245,.70),0 0 8px rgba(85,255,136,.48)}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"] .gv-target-comet{animation:none!important;opacity:1!important;transform:translate(-50%,-50%)!important}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"] .gv-target-comet i{opacity:0!important;transform:none!important}
#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"] .gv-target-comet i:nth-child(1){left:-1px!important;top:-1px!important;width:2px!important;height:2px!important;border-radius:50%!important;opacity:1!important;transform:none!important;background:#FFFFFF!important;box-shadow:0 0 2px 1px #FFFFFF,0 0 6px 2px #62D8FF!important}
@keyframes gv-target-comet-orbit{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}
@keyframes gv-target-status-pulse{0%{filter:drop-shadow(0 0 4px rgba(255,255,255,.98)) drop-shadow(0 0 10px rgba(98,216,255,.96))}10%{filter:drop-shadow(0 0 2.8px rgba(214,247,255,.76)) drop-shadow(0 0 8px rgba(98,216,255,.82))}32%{filter:drop-shadow(0 0 2px rgba(188,239,255,.56)) drop-shadow(0 0 6px rgba(98,216,255,.64))}58%{filter:drop-shadow(0 0 1px rgba(172,232,255,.34)) drop-shadow(0 0 3.5px rgba(98,216,255,.38))}86%{filter:drop-shadow(0 0 .5px rgba(160,225,255,.18)) drop-shadow(0 0 2px rgba(98,216,255,.22))}94%{filter:drop-shadow(0 0 2px rgba(255,255,255,.82)) drop-shadow(0 0 7px rgba(160,236,255,.76))}100%{filter:drop-shadow(0 0 5px #fff) drop-shadow(0 0 12px rgba(98,216,255,1))}}
@media (prefers-reduced-motion:reduce){#aladin-cosmic-command-test button.gv-menu-proxy .gv-menu-track{animation:none!important;box-shadow:0 0 4px rgba(215,243,255,.78)!important}#aladin-cosmic-command-test button.gv-target-proxy .gv-target-comet{animation:none!important;transform:rotate(35deg)!important}#aladin-cosmic-command-test button.gv-target-proxy[aria-pressed="true"] .gv-target-comet{transform:translate(-50%,-50%)!important}#aladin-cosmic-command-test .gv-target-status.gv-active,#aladin-cosmic-command-test .gv-coordinate-display{animation:none!important;filter:drop-shadow(0 0 3px rgba(255,255,255,.9)) drop-shadow(0 0 8px rgba(98,216,255,.9))!important}}
#aladin-cosmic-command-test .gv-target-status{grid-column:2 / 4!important;grid-row:2!important;justify-self:end!important;display:none!important;visibility:hidden!important;opacity:0!important;align-items:center!important;justify-content:center!important;flex-direction:column!important;width:140px!important;min-width:140px!important;max-width:140px!important;height:72px!important;min-height:72px!important;max-height:72px!important;margin:8px 6px 0 0!important;padding:6px 6px!important;box-sizing:border-box!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.88)!important;color:#D7F3FF!important;font:400 8px/1.35 "Space Age",sans-serif!important;text-align:center!important;white-space:nowrap!important;box-shadow:0 0 9px rgba(98,216,255,.34)!important;pointer-events:none!important}
#aladin-cosmic-command-test .gv-target-status>span{display:block!important;width:100%!important;text-align:center!important;white-space:nowrap!important}
#aladin-cosmic-command-test .gv-target-status.gv-active{display:flex!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;cursor:pointer!important;animation:gv-target-status-pulse 3s cubic-bezier(.35,.02,.18,1) infinite!important;will-change:filter}
#aladin-cosmic-command-test .gv-native-simbad-engine{position:absolute!important;left:-10000px!important;top:-10000px!important;width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;max-width:1px!important;max-height:1px!important;padding:0!important;margin:0!important;opacity:0!important;visibility:hidden!important;pointer-events:none!important;overflow:hidden!important}
#aladin-cosmic-command-test #gv-version-label{position:absolute!important;left:12px!important;bottom:12px!important;z-index:7100!important;display:block!important;visibility:visible!important;opacity:1!important;pointer-events:none!important;padding:6px 9px!important;border:1px solid var(--gv-version-color,#FFD166)!important;border-radius:5px!important;background:rgba(0,0,0,.84)!important;color:var(--gv-version-color,#FFD166)!important;font:400 12px/1.15 "Space Age",sans-serif!important;letter-spacing:.2px!important;text-shadow:0 0 7px var(--gv-version-glow,rgba(255,209,102,.65))!important;box-shadow:0 0 9px var(--gv-version-glow,rgba(255,209,102,.35))!important}
#aladin-cosmic-command-test #gv-random-galaxy-panel{position:absolute!important;right:12px!important;bottom:12px!important;z-index:7000!important;display:flex!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;flex-direction:column!important;align-items:flex-end!important;gap:6px!important;font-family:"Space Age",sans-serif!important}
#aladin-cosmic-command-test #gv-random-galaxy-name{max-width:320px!important;padding:5px 9px!important;border:1px solid #D7F4FF!important;border-radius:5px!important;background:rgba(0,0,0,.78)!important;color:#62D8FF!important;font-size:12px!important;font-weight:400!important;line-height:1.25!important;text-align:right!important;text-shadow:0 0 6px rgba(98,216,255,.55)!important;box-shadow:inset 0 0 5px rgba(98,216,255,.22),0 0 7px rgba(215,244,255,.68),0 0 16px rgba(98,216,255,.34)!important}
#aladin-cosmic-command-test #gv-galaxy-navigation{display:flex!important;gap:7px!important;pointer-events:auto!important}
#aladin-cosmic-command-test #gv-galaxy-navigation button{display:block!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;appearance:none!important;-webkit-appearance:none!important;padding:8px 12px!important;border:1px solid #D7F4FF!important;border-radius:6px!important;background:rgba(0,0,0,.82)!important;color:#7DF4FF!important;font:400 13px/1.1 "Space Age",sans-serif!important;cursor:pointer!important;touch-action:manipulation!important;box-shadow:inset 0 0 5px rgba(98,216,255,.22),0 0 7px rgba(215,244,255,.68),0 0 16px rgba(98,216,255,.34)!important}
#aladin-cosmic-command-test #gv-galaxy-navigation button:disabled{opacity:.45!important;cursor:default!important}
</style>
<div id="aladin-cosmic-command-test"></div>
"""))

display(Javascript(r"""
(() => {
    const aladinBundleUrl="https://aladin.cds.unistra.fr/AladinLite/api/v3/3.8.2/aladin.js";
    const curatedCatalogUrl="https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/discovery/beautiful-galaxy-catalog-beta.json";
    const discoveryCatalogUrl="https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/discovery/galaxy-catalog-beta.json";
    const reticleUrl="https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/viewer/artwork/GV-reticle-0001.svg";
    const targetIconUrl="https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/viewer/artwork/icon_target_vector.svg";
    const SPECTACULAR_WEIGHT=0.65,CURATED_WEIGHT=0.30,DISCOVERY_WEIGHT=0.05,MAX_NON_SPECTACULAR_RUN=6;
    async function fetchCuratedRecords(){const response=await fetch(curatedCatalogUrl+"?v="+Date.now(),{cache:"no-store"});if(!response.ok)throw new Error("CURATED CATALOG RETURNED HTTP "+response.status);const payload=await response.json();return Array.isArray(payload.targets)?payload.targets.filter(target=>target&&target.name).map((target,index)=>({primary_name:String(target.name),target_name:String(target.name),ra_deg:Number(target.ra_deg),dec_deg:Number(target.dec_deg),preferred_fov_deg:Number(target.fov)||0.18,morphology:String(target.object_type||"GALAXY"),source:"CURATED",source_id:"CURATED:"+String(index+1).padStart(4,"0"),spectacular:target.spectacular===true})):[]}
    async function fetchDiscoveryRecords(){const response=await fetch(discoveryCatalogUrl+"?v="+Date.now(),{cache:"no-store"});if(!response.ok)throw new Error("DISCOVERY CATALOG RETURNED HTTP "+response.status);const payload=await response.json();return Array.isArray(payload.records)?payload.records.filter(record=>record&&record.source==="SIMBAD").map(record=>({...record,spectacular:false})):[]}
    function recordKey(record){return String(record?.source||"")+"|"+String(record?.source_id||record?.primary_name||"")}
    function chooseFromPool(pool,currentRecord){if(!pool.length)return null;const candidates=pool.filter(record=>recordKey(record)!==recordKey(currentRecord));const usable=candidates.length?candidates:pool;return usable[Math.floor(Math.random()*usable.length)]}
    function chooseRecord(curatedRecords,discoveryRecords,currentRecord,nonSpectacularRun){const spectacularRecords=curatedRecords.filter(record=>record.spectacular),otherCuratedRecords=curatedRecords.filter(record=>!record.spectacular);if(nonSpectacularRun>=MAX_NON_SPECTACULAR_RUN&&spectacularRecords.length)return chooseFromPool(spectacularRecords,currentRecord);const roll=Math.random();if(roll<SPECTACULAR_WEIGHT&&spectacularRecords.length)return chooseFromPool(spectacularRecords,currentRecord);if(roll<SPECTACULAR_WEIGHT+CURATED_WEIGHT&&otherCuratedRecords.length)return chooseFromPool(otherCuratedRecords,currentRecord);if(discoveryRecords.length)return chooseFromPool(discoveryRecords,currentRecord);return chooseFromPool(spectacularRecords.length?spectacularRecords:otherCuratedRecords,currentRecord)}
    function targetFor(record){const ra=Number(record?.ra_deg),dec=Number(record?.dec_deg);if(Number.isFinite(ra)&&Number.isFinite(dec))return ra+" "+dec;return String(record?.target_name||record?.primary_name||"0 0").trim()}
    function fovFor(record){return Math.min(1.5,Math.max(0.18,Number(record?.preferred_fov_deg)||0.18))}
    function startGalaxyViewer(){
        if(!window.A||!window.A.init){console.error("GV-BETA-0006L STARTUP FAILURE: WINDOW.A WAS NOT CREATED");return}
        window.A.init.then(async()=>{
            const A=window.A,root=document.getElementById("aladin-cosmic-command-test");
            let curatedRecords=[],discoveryRecords=[];
            try{[curatedRecords,discoveryRecords]=await Promise.all([fetchCuratedRecords(),fetchDiscoveryRecords()])}catch(error){console.error("GV-BETA-0006L CATALOG FAILURE:",error)}
            let nonSpectacularRun=0;
            const firstRecord=chooseRecord(curatedRecords,discoveryRecords,null,nonSpectacularRun),initialTarget=firstRecord?targetFor(firstRecord):"0 0",initialFov=firstRecord?fovFor(firstRecord):0.18;
            const aladin=A.aladin("#aladin-cosmic-command-test",{target:initialTarget,survey:"P/DSS2/color",fov:initialFov,cooFrame:"ICRSd",projection:"MOL",showReticle:false,showZoomControl:false,showFullscreenControl:false,showLayersControl:false,showGotoControl:false,showCooGridControl:false,showSettingsControl:false,showSelectionModeControl:false,showColorPickerControl:false,showShareControl:false,showSimbadPointerControl:true,showProjectionControl:false,showStatusBar:false,showFrame:true,showFov:false,showCooLocation:true,showContextMenu:false,showCatalog:false,showCooGrid:false});
            window.aladin_cosmic_command_test=aladin;
            const centerReticle=document.createElement("img");centerReticle.id="gv-center-reticle";centerReticle.src=reticleUrl+"?v=6L-icy-neon-001";centerReticle.alt="";centerReticle.setAttribute("aria-hidden","true");root.appendChild(centerReticle);
            function wrapVisibleText(scope=root){const walker=document.createTreeWalker(scope,NodeFilter.SHOW_TEXT,{acceptNode(node){const parent=node.parentElement;if(!parent||!node.nodeValue.trim())return NodeFilter.FILTER_REJECT;if(parent.closest("script,style,svg,canvas,.gv-space-age-glyph,.gv-coordinate-display"))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{const span=document.createElement("span");span.className="gv-space-age-glyph";span.textContent=node.nodeValue.toUpperCase();node.replaceWith(span)});root.querySelectorAll("input").forEach(input=>{if(typeof input.value==="string")input.value=input.value.toUpperCase();if(input.placeholder)input.placeholder=input.placeholder.toUpperCase()})}
            function findCoordinateBox(){return root.querySelector(".aladin-location")||root.querySelector(".aladin-coordinates")}
            function formatCoordinateText(raw){let count=0;return String(raw??"").replace(/[-+]?\d+(?:\.\d+)?/g,token=>{if(count>=2)return token;const value=Number(token);count+=1;return Number.isFinite(value)?value.toFixed(4):token})}
            function activeCoordinateFrame(){const raw=String(root.querySelector(".aladin-cooFrame")?.textContent||aladin?.getFrame?.()||"ICRSD").toUpperCase();if(raw.includes("GAL"))return "GAL";if(raw.includes("ICRSD"))return "ICRSD";return "ICRS"}
            let coordinateGlowResumeTimer=0;
            function markCoordinateMovement(display){display.classList.add("gv-coordinate-moving");clearTimeout(coordinateGlowResumeTimer);coordinateGlowResumeTimer=setTimeout(()=>display.classList.remove("gv-coordinate-moving"),300)}
            function renderCoordinateGlyphs(container,value,digitCells){const text=String(value);if(container.dataset.gvCoordinateValue===text)return false;container.dataset.gvCoordinateValue=text;const fragment=document.createDocumentFragment();for(const character of text){const glyph=document.createElement("span");glyph.className="gv-coordinate-glyph";if(digitCells&&/\d/.test(character)){glyph.classList.add("gv-coordinate-digit");if(character==="1")glyph.classList.add("gv-coordinate-one")}else if(digitCells&&(character==="+"||character==="-"))glyph.classList.add("gv-coordinate-sign");else if(digitCells)glyph.classList.add("gv-coordinate-symbol");glyph.textContent=character;fragment.appendChild(glyph)}container.replaceChildren(fragment);return true}
            function formatCoordinatesFourDecimals(){const coordinateBox=findCoordinateBox();if(!coordinateBox)return;const input=coordinateBox.matches?.("input")?coordinateBox:coordinateBox.querySelector?.("input");const raw=input?input.value:coordinateBox.textContent;const formatted=formatCoordinateText(raw);if(input&&formatted!==input.value)input.value=formatted;else if(!input&&formatted!==coordinateBox.textContent)coordinateBox.textContent=formatted;const values=String(formatted).match(/[-+]?\d+(?:\.\d+)?/g);if(!values||values.length<2)return;coordinateBox.classList.add("gv-coordinate-presented");let display=coordinateBox.querySelector(".gv-coordinate-display");if(!display){display=document.createElement("span");display.className="gv-coordinate-display";display.setAttribute("aria-hidden","true");display.innerHTML='<span class="gv-coordinate-frame-label"></span><span class="gv-coordinate-axis gv-coordinate-longitude"></span><span class="gv-coordinate-divider"><span class="gv-coordinate-glyph">λ</span></span><span class="gv-coordinate-axis gv-coordinate-latitude"></span>';coordinateBox.appendChild(display)}const framePart=display.querySelector(".gv-coordinate-frame-label"),longitudePart=display.querySelector(".gv-coordinate-longitude"),latitudePart=display.querySelector(".gv-coordinate-latitude");const frame=activeCoordinateFrame(),longitude=values[0],latitude=values[1];const changed=renderCoordinateGlyphs(framePart,frame,false)|renderCoordinateGlyphs(longitudePart,longitude,true)|renderCoordinateGlyphs(latitudePart,latitude,true);if(changed)markCoordinateMovement(display)}
            function findNativeSimbadEngine(){const claimed=root.querySelector("button.gv-native-simbad-engine");if(claimed)return claimed;const direct=root.querySelector("button.aladin-simbadPointer-control,button.aladin-simbadPointerControl,button.aladin-btn[class*='simbadPointer']");if(direct)return direct;const wrapper=root.querySelector(".aladin-simbadPointer-control,.aladin-simbadPointerControl,[class*='simbadPointer']");return wrapper?.matches?.("button.aladin-btn")?wrapper:wrapper?.querySelector?.("button.aladin-btn")||null}
            function getViewerMenu(){let panel=root.querySelector(".gv-viewer-menu");if(panel)return panel;panel=document.createElement("div");panel.className="gv-viewer-menu";panel.setAttribute("role","menu");panel.setAttribute("aria-label","VIEWER OPTIONS PROTOTYPE");["PROJECTION","LAYERS","GRID","SURVEY","RETICLE ON/OFF"].forEach(label=>{const row=document.createElement("div");row.className="gv-viewer-menu-row";row.setAttribute("role","none");const labelButton=document.createElement("button");labelButton.type="button";labelButton.className="gv-viewer-menu-label";labelButton.setAttribute("role","menuitem");labelButton.textContent=label;const iconButton=document.createElement("button");iconButton.type="button";iconButton.className="gv-viewer-menu-icon";iconButton.setAttribute("role","menuitem");iconButton.setAttribute("aria-label",label+" ICON PLACEHOLDER");const selectRow=event=>{event.preventDefault();event.stopPropagation();panel.querySelectorAll(".gv-viewer-menu-row.gv-selected").forEach(selected=>selected.classList.remove("gv-selected"));void row.offsetWidth;row.classList.add("gv-selected");clearTimeout(row.gvSelectionTimer);row.gvSelectionTimer=setTimeout(()=>row.classList.remove("gv-selected"),700)};labelButton.addEventListener("click",selectRow);iconButton.addEventListener("click",selectRow);row.append(labelButton,iconButton);panel.appendChild(row)});root.appendChild(panel);wrapVisibleText(panel);return panel}
            function createMenuProxy(){let menu=root.querySelector("button.gv-menu-proxy");if(menu)return menu;menu=document.createElement("button");menu.type="button";menu.className="gv-menu-proxy";menu.title="VIEWER MENU";menu.setAttribute("aria-label","VIEWER MENU");menu.setAttribute("aria-expanded","false");menu.innerHTML='<span class="gv-menu-track" aria-hidden="true"></span><span class="gv-menu-track" aria-hidden="true"></span><span class="gv-menu-track" aria-hidden="true"></span>';menu.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();const panel=getViewerMenu(),open=!panel.classList.contains("gv-open");panel.classList.toggle("gv-open",open);menu.setAttribute("aria-expanded",open?"true":"false")});return menu}
            function getTargetStatus(){let status=root.querySelector(".gv-target-status");if(status)return status;status=document.createElement("div");status.className="gv-target-status";status.setAttribute("role","button");status.setAttribute("tabindex","0");status.setAttribute("aria-live","polite");status.setAttribute("aria-label","DEACTIVATE TARGET MODE AND RESUME NAVIGATION");status.setAttribute("title","TAP TO EXIT TARGET MODE AND RESUME NAVIGATION");status.innerHTML='<span>SELECT A GALAXY</span><span>OR A STAR</span><span>TAP HERE AGAIN</span><span>TO EXIT TARGET MODE</span>';return status}
            function createTargetProxy(){let proxy=root.querySelector("button.gv-target-proxy");if(proxy)return proxy;proxy=document.createElement("button");proxy.type="button";proxy.className="gv-target-proxy";proxy.title="SIMBAD TARGET";proxy.setAttribute("aria-label","SIMBAD TARGET");proxy.setAttribute("aria-pressed","false");proxy.innerHTML=`<img src="${targetIconUrl}?v=6L-icy-neon-001" alt="" aria-hidden="true" draggable="false"><span class="gv-target-comet" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></span>`;proxy.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();const active=proxy.getAttribute("aria-pressed")!=="true";proxy.setAttribute("aria-pressed",active?"true":"false");getTargetStatus().classList.toggle("gv-active",active);if(typeof aladin.useSimbadPointer==="function")aladin.useSimbadPointer(active);else findNativeSimbadEngine()?.click()});return proxy}
            function bindTargetStatus(proxy,status){if(status.dataset.gv6lBound==="true")return;status.dataset.gv6lBound="true";const deactivate=event=>{event.preventDefault();event.stopPropagation();if(proxy.getAttribute("aria-pressed")==="true")proxy.click()};status.addEventListener("click",deactivate);status.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "||event.key==="Spacebar")deactivate(event)})}
            function buildCoordinateTargetRow(){const frame=root.querySelector(".aladin-cooFrame"),coordinateBox=findCoordinateBox(),engine=findNativeSimbadEngine();if(!frame||!coordinateBox||!engine)return false;frame.classList.add("gv-native-coordinate-frame");frame.setAttribute("aria-hidden","true");frame.tabIndex=-1;engine.classList.add("gv-native-simbad-engine");engine.setAttribute("aria-hidden","true");engine.tabIndex=-1;let row=root.querySelector(".gv-coordinate-target-row");if(!row){row=document.createElement("div");row.className="gv-coordinate-target-row";root.appendChild(row)}const menu=createMenuProxy();if(menu.parentElement!==row)row.appendChild(menu);if(coordinateBox.parentElement!==row)row.appendChild(coordinateBox);const proxy=createTargetProxy();if(proxy.parentElement!==row)row.appendChild(proxy);const status=getTargetStatus();if(status.parentElement!==row)row.appendChild(status);getViewerMenu();bindTargetStatus(proxy,status);formatCoordinatesFourDecimals();wrapVisibleText(row);return row.children.length>=4}
            [150,350,700,1200,2200].forEach(delay=>setTimeout(buildCoordinateTargetRow,delay));
            const rowObserver=new MutationObserver(mutations=>{if(mutations.every(mutation=>mutation.target?.closest?.(".gv-coordinate-display")))return;buildCoordinateTargetRow();wrapVisibleText(root)});rowObserver.observe(root,{childList:true,subtree:true});setInterval(formatCoordinatesFourDecimals,250);
            const versionLabel=document.createElement("div");versionLabel.id="gv-version-label";versionLabel.textContent="V-6T";versionLabel.style.setProperty("--gv-version-color","#FFD166");versionLabel.style.setProperty("--gv-version-glow","rgba(255,209,102,.58)");root.appendChild(versionLabel);
            const panel=document.createElement("div");panel.id="gv-random-galaxy-panel";panel.innerHTML='<div id="gv-random-galaxy-name" role="status" aria-live="polite">1,000 GALAXIES · 250 SPECTACULAR</div><div id="gv-galaxy-navigation"><button id="gv-back-galaxy" type="button" disabled>BACK</button><button id="gv-next-galaxy" type="button" disabled>NEXT GALAXY</button></div>';root.appendChild(panel);wrapVisibleText(root);
            const nameLabel=panel.querySelector("#gv-random-galaxy-name"),backButton=panel.querySelector("#gv-back-galaxy"),nextButton=panel.querySelector("#gv-next-galaxy");let history=[],historyPosition=-1,navigating=false;
            function setVisibleText(element,text){element.textContent=String(text).toUpperCase();wrapVisibleText(element)}
            function deactivateTarget(){const proxy=root.querySelector("button.gv-target-proxy");if(proxy?.getAttribute("aria-pressed")==="true")proxy.click()}
            async function openGalaxy(record){if(!record||navigating)return;navigating=true;backButton.disabled=true;nextButton.disabled=true;try{const ra=Number(record?.ra_deg),dec=Number(record?.dec_deg),fov=fovFor(record);if(Number.isFinite(ra)&&Number.isFinite(dec))aladin.gotoRaDec(ra,dec);else await Promise.resolve(aladin.gotoObject(targetFor(record)));aladin.setFoV(fov);const category=record.spectacular?"SPECTACULAR":(record.source==="CURATED"?"BEAUTIFUL":"DISCOVERY"),type=String(record.morphology||"GALAXY").trim();setVisibleText(nameLabel,String(record.primary_name||"UNNAMED GALAXY").trim()+" · "+category+" · "+type+" · FOV "+fov.toFixed(2)+"°")}catch(error){setVisibleText(nameLabel,"COULD NOT RESOLVE "+String(record.primary_name||"GALAXY"));console.error("GV-BETA-0006L TARGET FAILURE:",error)}finally{navigating=false;backButton.disabled=historyPosition<=0;nextButton.disabled=!(curatedRecords.length||discoveryRecords.length)}}
            async function openNextGalaxy(){if(navigating)return;const current=historyPosition>=0?history[historyPosition]:null,nextRecord=chooseRecord(curatedRecords,discoveryRecords,current,nonSpectacularRun);if(!nextRecord)return;if(historyPosition<history.length-1)history=history.slice(0,historyPosition+1);history.push(nextRecord);historyPosition=history.length-1;nonSpectacularRun=nextRecord.spectacular?0:nonSpectacularRun+1;await openGalaxy(nextRecord)}
            async function openPreviousGalaxy(){if(navigating||historyPosition<=0)return;historyPosition-=1;await openGalaxy(history[historyPosition])}
            backButton.addEventListener("click",()=>{deactivateTarget();openPreviousGalaxy()});nextButton.addEventListener("click",()=>{deactivateTarget();openNextGalaxy()});if(firstRecord){history=[firstRecord];historyPosition=0;nonSpectacularRun=firstRecord.spectacular?0:1;await openGalaxy(firstRecord)}else setVisibleText(nameLabel,"GALAXY CATALOGS UNAVAILABLE");wrapVisibleText(root);
        }).catch(error=>console.error("GV-BETA-0006L STARTUP FAILURE:",error));
    }
    if(window.A&&window.A.init){startGalaxyViewer();return}
    let loader=document.querySelector('script[data-gv-aladin="3.8.2"]');
    if(loader){loader.addEventListener("load",startGalaxyViewer,{once:true});loader.addEventListener("error",()=>console.error("GV-BETA-0006L STARTUP FAILURE: OFFICIAL ALADIN 3.8.2 BUNDLE FAILED TO LOAD"),{once:true});return}
    loader=document.createElement("script");loader.src=aladinBundleUrl;loader.charset="utf-8";loader.dataset.gvAladin="3.8.2";loader.addEventListener("load",startGalaxyViewer,{once:true});loader.addEventListener("error",()=>console.error("GV-BETA-0006L STARTUP FAILURE: OFFICIAL ALADIN 3.8.2 BUNDLE FAILED TO LOAD"),{once:true});document.head.appendChild(loader);
})();
"""))

# GV-beta-0006T staged
