plugins { id 'com.android.application' }

android {
    namespace 'com.gear66me.galaxyviewer.webbrowser'
    compileSdk 35

    defaultConfig {
        applicationId 'com.gear66me.galaxyviewer.webbrowser'
        minSdk 29
        targetSdk 35
        versionCode 24
        versionName '0024'
    }
}
