export const REV='0028';
const NOVA='https://nova.astrometry.net';
const RAW='https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/viewer/image-databases';
const CATALOGS={Hubble:RAW+'/Hubble/databases/gv-hubble-galaxies-full-0025.json',JWST:RAW+'/JWST/databases/gv-jwst-galaxies-full-0002.json',Spitzer:RAW+'/Spitzer/databases/gv-spitzer-galaxies-full-0009.json',Chandra:RAW+'/Chandra/databases/gv-chandra-galaxies-full-0002.json'};
const PRED='https://raw.githubusercontent.com/gear66me-ui/Galaxy_Viewer/beta/viewer/image-databases/master-database/orientation-review/gv-registration-predictions-0001.json';
const IMAGE_TIMEOUT=15000;
export function json(o,status=200,extra={}){return new Response(JSON.stringify(o),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...extra}})}
const entries=d=>Array.isArray(d)?d:(d&&Array.isArray(d.entries)?d.entries:(d&&Array.isArray(d.galaxies)?d.galaxies:(d&&Array.isArray(d.records)?d.records:(d&&Array.isArray(d.items)?d.items:(d&&Array.isArray(d.data)?d.data:(d&&Array.isArray(d.catalog)?d.catalog:[]))))));
const n=v=>Number.isFinite(Number(v))?Number(v):null;
function images(r){const a=[];if(Array.isArray(r.jpegCandidates))a.push(...r.jpegCandidates);if(Array.isArray(r.imageCandidates))a.push(...r.imageCandidates);for(const k of ['selectedImageUrl','esaPublicationJpeg','githubImageUrl','publicationJpeg','imageUrl','jpegUrl','image'])if(r[k])a.push(r[k]);return [...new Set(a.filter(x=>typeof x==='string'&&/^https?:\/\//i.test(x.trim())).map(x=>x.trim()))]}
function slim(m,r){return{mission:m,archiveId:r.archiveId||r.id||null,name:r.name||r.title||r.designation||r.archiveId||'Unnamed',displayName:r.displayName||null,ra:n(r.ra??r.RA??r.raDeg),dec:n(r.dec??r.Dec??r.DEC??r.decDeg),fieldOfView:r.fieldOfView??r.fov??r.FOV??null,orientation:r.orientation??r.positionAngle??r.pa??null,imageCandidates:images(r),selectedImageUrl:r.selectedImageUrl||null,esaPublicationJpeg:r.esaPublicationJpeg||null,githubImageUrl:r.githubImageUrl||null,sourceUrl:r.sourceUrl||r.sourcePageUrl||r.archiveUrl||r.infoUrl||null}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export async function catalog(u){const m=u.searchParams.get('mission')||'Hubble',src=CATALOGS[m],limit=Math.min(300,Math.max(1,Number(u.searchParams.get('limit'))||200));if(!src)return json({ok:false,revision:REV,error:'unknown mission'},400);try{const r=await fetch(src,{cf:{cacheTtl:900,cacheEverything:true}});if(!r.ok)throw Error(m+' catalog HTTP '+r.status+' · '+src);const d=await r.json(),out=[];for(const x of entries(d)){const s=slim(m,x);if(Number.isFinite(s.ra)&&Number.isFinite(s.dec)&&s.imageCandidates.length)out.push(s)}if(u.searchParams.get('random')!=='0')shuffle(out);return json({ok:true,revision:REV,mission:m,source:src,totalUsable:out.length,count:Math.min(out.length,limit),records:out.slice(0,limit)})}catch(e){return json({ok:false,revision:REV,mission:m,source:src,error:String(e?.message||e)},502)}}
export async function predictions(){try{const r=await fetch(PRED,{cf:{cacheTtl:900,cacheEverything:true}});if(!r.ok)throw Error('predictions HTTP '+r.status);const d=await r.json();return json({ok:true,revision:REV,predictions:Array.isArray(d)?d:(d.predictions||[])})}catch(e){return json({ok:false,revision:REV,error:String(e?.message||e)},502)}}
function safeRemote(raw){const u=new URL(String(raw||''));if(!/^https?:$/.test(u.protocol))throw Error('image URL must use http(s)');const h=u.hostname.toLowerCase();if(h==='localhost'||h==='127.0.0.1'||h==='0.0.0.0'||h==='::1'||/^(10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/.test(h))throw Error('private image host blocked');return u}
async function timedFetch(url,init={},ms=IMAGE_TIMEOUT){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
export async function image(u,request){let remote;try{remote=safeRemote(u.searchParams.get('url'))}catch(e){return json({ok:false,revision:REV,error:String(e.message||e)},400,{'access-control-allow-origin':'*'})}const cache=caches.default,ck=new Request(new URL('/__gv0028_image?url='+encodeURIComponent(remote.href),request.url).href);const hit=await cache.match(ck);if(hit){const h=new Headers(hit.headers);h.set('x-gv-cache','HIT');h.set('access-control-allow-origin','*');return new Response(hit.body,{status:hit.status,headers:h})}try{const r=await timedFetch(remote.href,{headers:{accept:'image/avif,image/webp,image/apng,image/*,*/*;q=0.8','user-agent':'GalaxyViewerAstrometryCurator/0028'},redirect:'follow'});if(!r.ok)throw Error('source image HTTP '+r.status);const ct=(r.headers.get('content-type')||'').toLowerCase();if(ct&&!ct.startsWith('image/'))throw Error('source did not return an image · '+ct);const h=new Headers(r.headers);h.set('cache-control','public,max-age=604800');h.set('access-control-allow-origin','*');h.set('x-gv-cache','MISS');h.delete('set-cookie');const out=new Response(r.body,{status:200,headers:h});try{await cache.put(ck,out.clone())}catch{}return out}catch(e){return json({ok:false,revision:REV,source:remote.href,error:String(e?.message||e)},502,{'access-control-allow-origin':'*'})}}
async function novaPost(path,payload){const b=new URLSearchParams();b.set('request-json',JSON.stringify(payload));const r=await timedFetch(NOVA+path,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded;charset=UTF-8'},body:b.toString(),redirect:'follow'},30000);const t=await r.text();let j={};try{j=JSON.parse(t)}catch{}const apiError=j?.errormessage||j?.error||j?.message||null;if(!r.ok)throw Error('Astrometry.net '+path+' HTTP '+r.status+(apiError?' · '+apiError:''));if(j?.status==='error')throw Error('Astrometry.net '+path+' · '+(apiError||'API error'));return j}
async function novaGet(path){const r=await timedFetch(NOVA+path,{headers:{accept:'application/json'},redirect:'follow'},30000);const t=await r.text();let j={};try{j=JSON.parse(t)}catch{}const apiError=j?.errormessage||j?.error||j?.message||null;if(!r.ok)throw Error('Astrometry.net '+path+' HTTP '+r.status+(apiError?' · '+apiError:''));if(j?.status==='error')throw Error('Astrometry.net '+path+' · '+(apiError||'API error'));return j}
const finite=(v,k)=>{v=Number(v);if(!Number.isFinite(v))throw Error(k+' must be finite');return v},clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function norm(v){v=Number(v)||0;while(v>180)v-=360;while(v<=-180)v+=360;return v}
export async function solve(request,env){if(request.method!=='POST')return json({ok:false,revision:REV,error:'POST required'},405);let b;try{b=await request.json()}catch{return json({ok:false,revision:REV,error:'invalid JSON'},400)}try{const key=String(env?.ASTROMETRY_API_KEY||b.apikey||'').trim();if(!key)throw Error('ASTROMETRY_API_KEY is not configured');const url=String(b.image_url||'').trim();if(!/^https?:\/\//i.test(url))throw Error('source image URL is invalid');const width=Math.max(1,Math.round(finite(b.width,'width'))),height=Math.max(1,Math.round(finite(b.height,'height'))),strategy=String(b.strategy||'seeded-scale'),ra=n(b.ra),dec=n(b.dec),fov=n(b.fov);if(!['seeded-scale','seeded-relaxed','blind'].includes(strategy))throw Error('invalid solve strategy');const login=await novaPost('/api/login',{apikey:key});if(login.status!=='success'||!login.session)throw Error(login.errormessage||'Astrometry.net login failed');const up={session:login.session,url,allow_commercial_use:'d',allow_modifications:'d',publicly_visible:'n'};if(strategy==='seeded-scale'){up.downsample_factor=2;if(fov!==null&&fov>0){up.scale_units='degwidth';up.scale_type='ul';up.scale_lower=Math.max(fov*.20,.0001);up.scale_upper=Math.min(Math.max(fov*5,up.scale_lower*2),180)}if(ra!==null&&dec!==null){up.center_ra=ra;up.center_dec=dec;up.radius=fov!==null&&fov>0?clamp(fov*4,.05,30):10}}else if(strategy==='seeded-relaxed'){up.downsample_factor=1;up.positional_error=2;if(ra!==null&&dec!==null){up.center_ra=ra;up.center_dec=dec;up.radius=fov!==null&&fov>0?clamp(Math.max(fov*12,2),2,90):30}}else{up.downsample_factor=1;up.positional_error=2}const sub=await novaPost('/api/url_upload',up);if(sub.status!=='success'||!sub.subid)throw Error(sub.errormessage||'Astrometry.net submission failed');return json({ok:true,revision:REV,subid:sub.subid,strategy,width,height,search:{parity:'both (parameter omitted)',scale_units:up.scale_units||null,scale_lower:up.scale_lower||null,scale_upper:up.scale_upper||null,center_ra:up.center_ra??null,center_dec:up.center_dec??null,radius:up.radius??null}})}catch(e){return json({ok:false,revision:REV,error:String(e?.message||e)},400)}}
export async function status(u){try{const subid=Number(u.searchParams.get('subid')),width=Math.max(1,Number(u.searchParams.get('width'))||1),height=Math.max(1,Number(u.searchParams.get('height'))||1);if(!Number.isInteger(subid)||subid<=0)throw Error('invalid submission id');const si=await novaGet('/api/submissions/'+subid),jobs=(si.jobs||[]).filter(Boolean);if(!jobs.length)return json(si.processing_finished?{ok:true,revision:REV,status:'error',phase:'FAILED',message:'submission '+subid+' finished without a solution'}:{ok:true,revision:REV,status:'running',phase:'QUEUE',message:'submission '+subid});const jobid=jobs.at(-1),js=await novaGet('/api/jobs/'+jobid);if(js.status==='failure')return json({ok:true,revision:REV,status:'error',phase:'FAILED',message:'job '+jobid+' failed'});if(js.status!=='success')return json({ok:true,revision:REV,status:'running',phase:'SOLVING',message:'job '+jobid+' · '+(js.status||'processing')});const cal=await novaGet('/api/jobs/'+jobid+'/calibration/'),pix=Number(cal.pixscale);if(!Number.isFinite(pix)||pix<=0)throw Error('invalid pixel scale');const fx=pix*width/3600,fy=pix*height/3600,o=Number(cal.orientation)||0;return json({ok:true,revision:REV,status:'success',phase:'SOLVED',result:{revision:REV,jobid,subid,ra:Number(cal.ra),dec:Number(cal.dec),pixscale_arcsec_per_pixel:pix,fov_x_deg:fx,fov_y_deg:fy,astrometry_orientation_deg:o,aladin_rotation_deg:norm(-o),parity:cal.parity??null}})}catch(e){return json({ok:false,revision:REV,error:String(e?.message||e)},400)}}
function parseTsv(t){const lines=String(t||'').split(/\r?\n/).filter(l=>l&&!l.startsWith('#')),hi=lines.findIndex(l=>/\bRA_ICRS\b/.test(l)&&/\bDE_ICRS\b/.test(l));if(hi<0)return[];const h=lines[hi].split('\t').map(x=>x.trim()),out=[];for(const line of lines.slice(hi+1)){if(/^[-\t ]+$/.test(line))continue;const c=line.split('\t');if(c.length<h.length)continue;const row={};h.forEach((k,i)=>row[k]=c[i]?.trim());const ra=Number(row.RA_ICRS),dec=Number(row.DE_ICRS),g=Number(row.Gmag);if(Number.isFinite(ra)&&Number.isFinite(dec))out.push({source_id:row.Source||null,ra,dec,gmag:Number.isFinite(g)?g:null})}return out}
export async function gaia(u){try{const ra=finite(u.searchParams.get('ra'),'ra'),dec=finite(u.searchParams.get('dec'),'dec'),radius=clamp(finite(u.searchParams.get('radius_deg')||.1,'radius_deg'),.001,2),limit=Math.min(200,Math.max(1,Number(u.searchParams.get('limit'))||100));const q=new URL('https://vizier.cds.unistra.fr/viz-bin/asu-tsv');q.searchParams.set('-source','I/355/gaiadr3');q.searchParams.set('-c',ra+' '+dec);q.searchParams.set('-c.r',String(radius));q.searchParams.set('-c.u','deg');q.searchParams.set('-out','Source,RA_ICRS,DE_ICRS,Gmag');q.searchParams.set('-out.max',String(limit));q.searchParams.set('-sort','Gmag');const r=await timedFetch(q.toString(),{headers:{accept:'text/tab-separated-values,text/plain'}},30000),t=await r.text();if(!r.ok)throw Error('VizieR Gaia DR3 HTTP '+r.status);const stars=parseTsv(t);return json({ok:true,revision:REV,service:'CDS VizieR / Astroquery-equivalent',catalog:'I/355/gaiadr3',ra,dec,radius_deg:radius,count:stars.length,stars})}catch(e){return json({ok:false,revision:REV,error:String(e?.message||e)},400)}}
